
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FacultyProfile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model FacultyProfile
 * 
 */
export type FacultyProfileModel = runtime.Types.Result.DefaultSelection<Prisma.$FacultyProfilePayload>

export type AggregateFacultyProfile = {
  _count: FacultyProfileCountAggregateOutputType | null
  _min: FacultyProfileMinAggregateOutputType | null
  _max: FacultyProfileMaxAggregateOutputType | null
}

export type FacultyProfileMinAggregateOutputType = {
  id: string | null
  userId: string | null
  department: string | null
  designation: string | null
}

export type FacultyProfileMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  department: string | null
  designation: string | null
}

export type FacultyProfileCountAggregateOutputType = {
  id: number
  userId: number
  department: number
  designation: number
  expertise: number
  _all: number
}


export type FacultyProfileMinAggregateInputType = {
  id?: true
  userId?: true
  department?: true
  designation?: true
}

export type FacultyProfileMaxAggregateInputType = {
  id?: true
  userId?: true
  department?: true
  designation?: true
}

export type FacultyProfileCountAggregateInputType = {
  id?: true
  userId?: true
  department?: true
  designation?: true
  expertise?: true
  _all?: true
}

export type FacultyProfileAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FacultyProfile to aggregate.
   */
  where?: Prisma.FacultyProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FacultyProfiles to fetch.
   */
  orderBy?: Prisma.FacultyProfileOrderByWithRelationInput | Prisma.FacultyProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FacultyProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FacultyProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FacultyProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FacultyProfiles
  **/
  _count?: true | FacultyProfileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FacultyProfileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FacultyProfileMaxAggregateInputType
}

export type GetFacultyProfileAggregateType<T extends FacultyProfileAggregateArgs> = {
      [P in keyof T & keyof AggregateFacultyProfile]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFacultyProfile[P]>
    : Prisma.GetScalarType<T[P], AggregateFacultyProfile[P]>
}




export type FacultyProfileGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FacultyProfileWhereInput
  orderBy?: Prisma.FacultyProfileOrderByWithAggregationInput | Prisma.FacultyProfileOrderByWithAggregationInput[]
  by: Prisma.FacultyProfileScalarFieldEnum[] | Prisma.FacultyProfileScalarFieldEnum
  having?: Prisma.FacultyProfileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FacultyProfileCountAggregateInputType | true
  _min?: FacultyProfileMinAggregateInputType
  _max?: FacultyProfileMaxAggregateInputType
}

export type FacultyProfileGroupByOutputType = {
  id: string
  userId: string
  department: string
  designation: string
  expertise: string[]
  _count: FacultyProfileCountAggregateOutputType | null
  _min: FacultyProfileMinAggregateOutputType | null
  _max: FacultyProfileMaxAggregateOutputType | null
}

type GetFacultyProfileGroupByPayload<T extends FacultyProfileGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FacultyProfileGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FacultyProfileGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FacultyProfileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FacultyProfileGroupByOutputType[P]>
      }
    >
  >



export type FacultyProfileWhereInput = {
  AND?: Prisma.FacultyProfileWhereInput | Prisma.FacultyProfileWhereInput[]
  OR?: Prisma.FacultyProfileWhereInput[]
  NOT?: Prisma.FacultyProfileWhereInput | Prisma.FacultyProfileWhereInput[]
  id?: Prisma.StringFilter<"FacultyProfile"> | string
  userId?: Prisma.StringFilter<"FacultyProfile"> | string
  department?: Prisma.StringFilter<"FacultyProfile"> | string
  designation?: Prisma.StringFilter<"FacultyProfile"> | string
  expertise?: Prisma.StringNullableListFilter<"FacultyProfile">
  User?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  Project?: Prisma.ProjectListRelationFilter
}

export type FacultyProfileOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  department?: Prisma.SortOrder
  designation?: Prisma.SortOrder
  expertise?: Prisma.SortOrder
  User?: Prisma.UserOrderByWithRelationInput
  Project?: Prisma.ProjectOrderByRelationAggregateInput
}

export type FacultyProfileWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId?: string
  AND?: Prisma.FacultyProfileWhereInput | Prisma.FacultyProfileWhereInput[]
  OR?: Prisma.FacultyProfileWhereInput[]
  NOT?: Prisma.FacultyProfileWhereInput | Prisma.FacultyProfileWhereInput[]
  department?: Prisma.StringFilter<"FacultyProfile"> | string
  designation?: Prisma.StringFilter<"FacultyProfile"> | string
  expertise?: Prisma.StringNullableListFilter<"FacultyProfile">
  User?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  Project?: Prisma.ProjectListRelationFilter
}, "id" | "userId">

export type FacultyProfileOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  department?: Prisma.SortOrder
  designation?: Prisma.SortOrder
  expertise?: Prisma.SortOrder
  _count?: Prisma.FacultyProfileCountOrderByAggregateInput
  _max?: Prisma.FacultyProfileMaxOrderByAggregateInput
  _min?: Prisma.FacultyProfileMinOrderByAggregateInput
}

export type FacultyProfileScalarWhereWithAggregatesInput = {
  AND?: Prisma.FacultyProfileScalarWhereWithAggregatesInput | Prisma.FacultyProfileScalarWhereWithAggregatesInput[]
  OR?: Prisma.FacultyProfileScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FacultyProfileScalarWhereWithAggregatesInput | Prisma.FacultyProfileScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FacultyProfile"> | string
  userId?: Prisma.StringWithAggregatesFilter<"FacultyProfile"> | string
  department?: Prisma.StringWithAggregatesFilter<"FacultyProfile"> | string
  designation?: Prisma.StringWithAggregatesFilter<"FacultyProfile"> | string
  expertise?: Prisma.StringNullableListFilter<"FacultyProfile">
}

export type FacultyProfileCreateInput = {
  id: string
  department: string
  designation: string
  expertise?: Prisma.FacultyProfileCreateexpertiseInput | string[]
  User: Prisma.UserCreateNestedOneWithoutFacultyProfileInput
  Project?: Prisma.ProjectCreateNestedManyWithoutFacultyProfileInput
}

export type FacultyProfileUncheckedCreateInput = {
  id: string
  userId: string
  department: string
  designation: string
  expertise?: Prisma.FacultyProfileCreateexpertiseInput | string[]
  Project?: Prisma.ProjectUncheckedCreateNestedManyWithoutFacultyProfileInput
}

export type FacultyProfileUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  designation?: Prisma.StringFieldUpdateOperationsInput | string
  expertise?: Prisma.FacultyProfileUpdateexpertiseInput | string[]
  User?: Prisma.UserUpdateOneRequiredWithoutFacultyProfileNestedInput
  Project?: Prisma.ProjectUpdateManyWithoutFacultyProfileNestedInput
}

export type FacultyProfileUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  designation?: Prisma.StringFieldUpdateOperationsInput | string
  expertise?: Prisma.FacultyProfileUpdateexpertiseInput | string[]
  Project?: Prisma.ProjectUncheckedUpdateManyWithoutFacultyProfileNestedInput
}

export type FacultyProfileCreateManyInput = {
  id: string
  userId: string
  department: string
  designation: string
  expertise?: Prisma.FacultyProfileCreateexpertiseInput | string[]
}

export type FacultyProfileUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  designation?: Prisma.StringFieldUpdateOperationsInput | string
  expertise?: Prisma.FacultyProfileUpdateexpertiseInput | string[]
}

export type FacultyProfileUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  designation?: Prisma.StringFieldUpdateOperationsInput | string
  expertise?: Prisma.FacultyProfileUpdateexpertiseInput | string[]
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type FacultyProfileCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  department?: Prisma.SortOrder
  designation?: Prisma.SortOrder
  expertise?: Prisma.SortOrder
}

export type FacultyProfileMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  department?: Prisma.SortOrder
  designation?: Prisma.SortOrder
}

export type FacultyProfileMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  department?: Prisma.SortOrder
  designation?: Prisma.SortOrder
}

export type FacultyProfileNullableScalarRelationFilter = {
  is?: Prisma.FacultyProfileWhereInput | null
  isNot?: Prisma.FacultyProfileWhereInput | null
}

export type FacultyProfileCreateexpertiseInput = {
  set: string[]
}

export type FacultyProfileUpdateexpertiseInput = {
  set?: string[]
  push?: string | string[]
}

export type FacultyProfileCreateNestedOneWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.FacultyProfileCreateWithoutProjectInput, Prisma.FacultyProfileUncheckedCreateWithoutProjectInput>
  connectOrCreate?: Prisma.FacultyProfileCreateOrConnectWithoutProjectInput
  connect?: Prisma.FacultyProfileWhereUniqueInput
}

export type FacultyProfileUpdateOneWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.FacultyProfileCreateWithoutProjectInput, Prisma.FacultyProfileUncheckedCreateWithoutProjectInput>
  connectOrCreate?: Prisma.FacultyProfileCreateOrConnectWithoutProjectInput
  upsert?: Prisma.FacultyProfileUpsertWithoutProjectInput
  disconnect?: Prisma.FacultyProfileWhereInput | boolean
  delete?: Prisma.FacultyProfileWhereInput | boolean
  connect?: Prisma.FacultyProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FacultyProfileUpdateToOneWithWhereWithoutProjectInput, Prisma.FacultyProfileUpdateWithoutProjectInput>, Prisma.FacultyProfileUncheckedUpdateWithoutProjectInput>
}

export type FacultyProfileCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.FacultyProfileCreateWithoutUserInput, Prisma.FacultyProfileUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.FacultyProfileCreateOrConnectWithoutUserInput
  connect?: Prisma.FacultyProfileWhereUniqueInput
}

export type FacultyProfileUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.FacultyProfileCreateWithoutUserInput, Prisma.FacultyProfileUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.FacultyProfileCreateOrConnectWithoutUserInput
  connect?: Prisma.FacultyProfileWhereUniqueInput
}

export type FacultyProfileUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.FacultyProfileCreateWithoutUserInput, Prisma.FacultyProfileUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.FacultyProfileCreateOrConnectWithoutUserInput
  upsert?: Prisma.FacultyProfileUpsertWithoutUserInput
  disconnect?: Prisma.FacultyProfileWhereInput | boolean
  delete?: Prisma.FacultyProfileWhereInput | boolean
  connect?: Prisma.FacultyProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FacultyProfileUpdateToOneWithWhereWithoutUserInput, Prisma.FacultyProfileUpdateWithoutUserInput>, Prisma.FacultyProfileUncheckedUpdateWithoutUserInput>
}

export type FacultyProfileUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.FacultyProfileCreateWithoutUserInput, Prisma.FacultyProfileUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.FacultyProfileCreateOrConnectWithoutUserInput
  upsert?: Prisma.FacultyProfileUpsertWithoutUserInput
  disconnect?: Prisma.FacultyProfileWhereInput | boolean
  delete?: Prisma.FacultyProfileWhereInput | boolean
  connect?: Prisma.FacultyProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FacultyProfileUpdateToOneWithWhereWithoutUserInput, Prisma.FacultyProfileUpdateWithoutUserInput>, Prisma.FacultyProfileUncheckedUpdateWithoutUserInput>
}

export type FacultyProfileCreateWithoutProjectInput = {
  id: string
  department: string
  designation: string
  expertise?: Prisma.FacultyProfileCreateexpertiseInput | string[]
  User: Prisma.UserCreateNestedOneWithoutFacultyProfileInput
}

export type FacultyProfileUncheckedCreateWithoutProjectInput = {
  id: string
  userId: string
  department: string
  designation: string
  expertise?: Prisma.FacultyProfileCreateexpertiseInput | string[]
}

export type FacultyProfileCreateOrConnectWithoutProjectInput = {
  where: Prisma.FacultyProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.FacultyProfileCreateWithoutProjectInput, Prisma.FacultyProfileUncheckedCreateWithoutProjectInput>
}

export type FacultyProfileUpsertWithoutProjectInput = {
  update: Prisma.XOR<Prisma.FacultyProfileUpdateWithoutProjectInput, Prisma.FacultyProfileUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.FacultyProfileCreateWithoutProjectInput, Prisma.FacultyProfileUncheckedCreateWithoutProjectInput>
  where?: Prisma.FacultyProfileWhereInput
}

export type FacultyProfileUpdateToOneWithWhereWithoutProjectInput = {
  where?: Prisma.FacultyProfileWhereInput
  data: Prisma.XOR<Prisma.FacultyProfileUpdateWithoutProjectInput, Prisma.FacultyProfileUncheckedUpdateWithoutProjectInput>
}

export type FacultyProfileUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  designation?: Prisma.StringFieldUpdateOperationsInput | string
  expertise?: Prisma.FacultyProfileUpdateexpertiseInput | string[]
  User?: Prisma.UserUpdateOneRequiredWithoutFacultyProfileNestedInput
}

export type FacultyProfileUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  designation?: Prisma.StringFieldUpdateOperationsInput | string
  expertise?: Prisma.FacultyProfileUpdateexpertiseInput | string[]
}

export type FacultyProfileCreateWithoutUserInput = {
  id: string
  department: string
  designation: string
  expertise?: Prisma.FacultyProfileCreateexpertiseInput | string[]
  Project?: Prisma.ProjectCreateNestedManyWithoutFacultyProfileInput
}

export type FacultyProfileUncheckedCreateWithoutUserInput = {
  id: string
  department: string
  designation: string
  expertise?: Prisma.FacultyProfileCreateexpertiseInput | string[]
  Project?: Prisma.ProjectUncheckedCreateNestedManyWithoutFacultyProfileInput
}

export type FacultyProfileCreateOrConnectWithoutUserInput = {
  where: Prisma.FacultyProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.FacultyProfileCreateWithoutUserInput, Prisma.FacultyProfileUncheckedCreateWithoutUserInput>
}

export type FacultyProfileUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.FacultyProfileUpdateWithoutUserInput, Prisma.FacultyProfileUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.FacultyProfileCreateWithoutUserInput, Prisma.FacultyProfileUncheckedCreateWithoutUserInput>
  where?: Prisma.FacultyProfileWhereInput
}

export type FacultyProfileUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.FacultyProfileWhereInput
  data: Prisma.XOR<Prisma.FacultyProfileUpdateWithoutUserInput, Prisma.FacultyProfileUncheckedUpdateWithoutUserInput>
}

export type FacultyProfileUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  designation?: Prisma.StringFieldUpdateOperationsInput | string
  expertise?: Prisma.FacultyProfileUpdateexpertiseInput | string[]
  Project?: Prisma.ProjectUpdateManyWithoutFacultyProfileNestedInput
}

export type FacultyProfileUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  designation?: Prisma.StringFieldUpdateOperationsInput | string
  expertise?: Prisma.FacultyProfileUpdateexpertiseInput | string[]
  Project?: Prisma.ProjectUncheckedUpdateManyWithoutFacultyProfileNestedInput
}


/**
 * Count Type FacultyProfileCountOutputType
 */

export type FacultyProfileCountOutputType = {
  Project: number
}

export type FacultyProfileCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Project?: boolean | FacultyProfileCountOutputTypeCountProjectArgs
}

/**
 * FacultyProfileCountOutputType without action
 */
export type FacultyProfileCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FacultyProfileCountOutputType
   */
  select?: Prisma.FacultyProfileCountOutputTypeSelect<ExtArgs> | null
}

/**
 * FacultyProfileCountOutputType without action
 */
export type FacultyProfileCountOutputTypeCountProjectArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProjectWhereInput
}


export type FacultyProfileSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  department?: boolean
  designation?: boolean
  expertise?: boolean
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  Project?: boolean | Prisma.FacultyProfile$ProjectArgs<ExtArgs>
  _count?: boolean | Prisma.FacultyProfileCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["facultyProfile"]>

export type FacultyProfileSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  department?: boolean
  designation?: boolean
  expertise?: boolean
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["facultyProfile"]>

export type FacultyProfileSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  department?: boolean
  designation?: boolean
  expertise?: boolean
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["facultyProfile"]>

export type FacultyProfileSelectScalar = {
  id?: boolean
  userId?: boolean
  department?: boolean
  designation?: boolean
  expertise?: boolean
}

export type FacultyProfileOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "department" | "designation" | "expertise", ExtArgs["result"]["facultyProfile"]>
export type FacultyProfileInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  Project?: boolean | Prisma.FacultyProfile$ProjectArgs<ExtArgs>
  _count?: boolean | Prisma.FacultyProfileCountOutputTypeDefaultArgs<ExtArgs>
}
export type FacultyProfileIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type FacultyProfileIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $FacultyProfilePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FacultyProfile"
  objects: {
    User: Prisma.$UserPayload<ExtArgs>
    Project: Prisma.$ProjectPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    department: string
    designation: string
    expertise: string[]
  }, ExtArgs["result"]["facultyProfile"]>
  composites: {}
}

export type FacultyProfileGetPayload<S extends boolean | null | undefined | FacultyProfileDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FacultyProfilePayload, S>

export type FacultyProfileCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FacultyProfileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FacultyProfileCountAggregateInputType | true
  }

export interface FacultyProfileDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FacultyProfile'], meta: { name: 'FacultyProfile' } }
  /**
   * Find zero or one FacultyProfile that matches the filter.
   * @param {FacultyProfileFindUniqueArgs} args - Arguments to find a FacultyProfile
   * @example
   * // Get one FacultyProfile
   * const facultyProfile = await prisma.facultyProfile.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FacultyProfileFindUniqueArgs>(args: Prisma.SelectSubset<T, FacultyProfileFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FacultyProfileClient<runtime.Types.Result.GetResult<Prisma.$FacultyProfilePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FacultyProfile that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FacultyProfileFindUniqueOrThrowArgs} args - Arguments to find a FacultyProfile
   * @example
   * // Get one FacultyProfile
   * const facultyProfile = await prisma.facultyProfile.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FacultyProfileFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FacultyProfileFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FacultyProfileClient<runtime.Types.Result.GetResult<Prisma.$FacultyProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FacultyProfile that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FacultyProfileFindFirstArgs} args - Arguments to find a FacultyProfile
   * @example
   * // Get one FacultyProfile
   * const facultyProfile = await prisma.facultyProfile.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FacultyProfileFindFirstArgs>(args?: Prisma.SelectSubset<T, FacultyProfileFindFirstArgs<ExtArgs>>): Prisma.Prisma__FacultyProfileClient<runtime.Types.Result.GetResult<Prisma.$FacultyProfilePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FacultyProfile that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FacultyProfileFindFirstOrThrowArgs} args - Arguments to find a FacultyProfile
   * @example
   * // Get one FacultyProfile
   * const facultyProfile = await prisma.facultyProfile.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FacultyProfileFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FacultyProfileFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FacultyProfileClient<runtime.Types.Result.GetResult<Prisma.$FacultyProfilePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FacultyProfiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FacultyProfileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FacultyProfiles
   * const facultyProfiles = await prisma.facultyProfile.findMany()
   * 
   * // Get first 10 FacultyProfiles
   * const facultyProfiles = await prisma.facultyProfile.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const facultyProfileWithIdOnly = await prisma.facultyProfile.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FacultyProfileFindManyArgs>(args?: Prisma.SelectSubset<T, FacultyProfileFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FacultyProfilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FacultyProfile.
   * @param {FacultyProfileCreateArgs} args - Arguments to create a FacultyProfile.
   * @example
   * // Create one FacultyProfile
   * const FacultyProfile = await prisma.facultyProfile.create({
   *   data: {
   *     // ... data to create a FacultyProfile
   *   }
   * })
   * 
   */
  create<T extends FacultyProfileCreateArgs>(args: Prisma.SelectSubset<T, FacultyProfileCreateArgs<ExtArgs>>): Prisma.Prisma__FacultyProfileClient<runtime.Types.Result.GetResult<Prisma.$FacultyProfilePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FacultyProfiles.
   * @param {FacultyProfileCreateManyArgs} args - Arguments to create many FacultyProfiles.
   * @example
   * // Create many FacultyProfiles
   * const facultyProfile = await prisma.facultyProfile.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FacultyProfileCreateManyArgs>(args?: Prisma.SelectSubset<T, FacultyProfileCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FacultyProfiles and returns the data saved in the database.
   * @param {FacultyProfileCreateManyAndReturnArgs} args - Arguments to create many FacultyProfiles.
   * @example
   * // Create many FacultyProfiles
   * const facultyProfile = await prisma.facultyProfile.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FacultyProfiles and only return the `id`
   * const facultyProfileWithIdOnly = await prisma.facultyProfile.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FacultyProfileCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FacultyProfileCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FacultyProfilePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FacultyProfile.
   * @param {FacultyProfileDeleteArgs} args - Arguments to delete one FacultyProfile.
   * @example
   * // Delete one FacultyProfile
   * const FacultyProfile = await prisma.facultyProfile.delete({
   *   where: {
   *     // ... filter to delete one FacultyProfile
   *   }
   * })
   * 
   */
  delete<T extends FacultyProfileDeleteArgs>(args: Prisma.SelectSubset<T, FacultyProfileDeleteArgs<ExtArgs>>): Prisma.Prisma__FacultyProfileClient<runtime.Types.Result.GetResult<Prisma.$FacultyProfilePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FacultyProfile.
   * @param {FacultyProfileUpdateArgs} args - Arguments to update one FacultyProfile.
   * @example
   * // Update one FacultyProfile
   * const facultyProfile = await prisma.facultyProfile.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FacultyProfileUpdateArgs>(args: Prisma.SelectSubset<T, FacultyProfileUpdateArgs<ExtArgs>>): Prisma.Prisma__FacultyProfileClient<runtime.Types.Result.GetResult<Prisma.$FacultyProfilePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FacultyProfiles.
   * @param {FacultyProfileDeleteManyArgs} args - Arguments to filter FacultyProfiles to delete.
   * @example
   * // Delete a few FacultyProfiles
   * const { count } = await prisma.facultyProfile.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FacultyProfileDeleteManyArgs>(args?: Prisma.SelectSubset<T, FacultyProfileDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FacultyProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FacultyProfileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FacultyProfiles
   * const facultyProfile = await prisma.facultyProfile.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FacultyProfileUpdateManyArgs>(args: Prisma.SelectSubset<T, FacultyProfileUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FacultyProfiles and returns the data updated in the database.
   * @param {FacultyProfileUpdateManyAndReturnArgs} args - Arguments to update many FacultyProfiles.
   * @example
   * // Update many FacultyProfiles
   * const facultyProfile = await prisma.facultyProfile.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FacultyProfiles and only return the `id`
   * const facultyProfileWithIdOnly = await prisma.facultyProfile.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FacultyProfileUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FacultyProfileUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FacultyProfilePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FacultyProfile.
   * @param {FacultyProfileUpsertArgs} args - Arguments to update or create a FacultyProfile.
   * @example
   * // Update or create a FacultyProfile
   * const facultyProfile = await prisma.facultyProfile.upsert({
   *   create: {
   *     // ... data to create a FacultyProfile
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FacultyProfile we want to update
   *   }
   * })
   */
  upsert<T extends FacultyProfileUpsertArgs>(args: Prisma.SelectSubset<T, FacultyProfileUpsertArgs<ExtArgs>>): Prisma.Prisma__FacultyProfileClient<runtime.Types.Result.GetResult<Prisma.$FacultyProfilePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FacultyProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FacultyProfileCountArgs} args - Arguments to filter FacultyProfiles to count.
   * @example
   * // Count the number of FacultyProfiles
   * const count = await prisma.facultyProfile.count({
   *   where: {
   *     // ... the filter for the FacultyProfiles we want to count
   *   }
   * })
  **/
  count<T extends FacultyProfileCountArgs>(
    args?: Prisma.Subset<T, FacultyProfileCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FacultyProfileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FacultyProfile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FacultyProfileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FacultyProfileAggregateArgs>(args: Prisma.Subset<T, FacultyProfileAggregateArgs>): Prisma.PrismaPromise<GetFacultyProfileAggregateType<T>>

  /**
   * Group by FacultyProfile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FacultyProfileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FacultyProfileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FacultyProfileGroupByArgs['orderBy'] }
      : { orderBy?: FacultyProfileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FacultyProfileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFacultyProfileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FacultyProfile model
 */
readonly fields: FacultyProfileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FacultyProfile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FacultyProfileClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  User<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  Project<T extends Prisma.FacultyProfile$ProjectArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FacultyProfile$ProjectArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FacultyProfile model
 */
export interface FacultyProfileFieldRefs {
  readonly id: Prisma.FieldRef<"FacultyProfile", 'String'>
  readonly userId: Prisma.FieldRef<"FacultyProfile", 'String'>
  readonly department: Prisma.FieldRef<"FacultyProfile", 'String'>
  readonly designation: Prisma.FieldRef<"FacultyProfile", 'String'>
  readonly expertise: Prisma.FieldRef<"FacultyProfile", 'String[]'>
}
    

// Custom InputTypes
/**
 * FacultyProfile findUnique
 */
export type FacultyProfileFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FacultyProfile
   */
  select?: Prisma.FacultyProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FacultyProfile
   */
  omit?: Prisma.FacultyProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FacultyProfileInclude<ExtArgs> | null
  /**
   * Filter, which FacultyProfile to fetch.
   */
  where: Prisma.FacultyProfileWhereUniqueInput
}

/**
 * FacultyProfile findUniqueOrThrow
 */
export type FacultyProfileFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FacultyProfile
   */
  select?: Prisma.FacultyProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FacultyProfile
   */
  omit?: Prisma.FacultyProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FacultyProfileInclude<ExtArgs> | null
  /**
   * Filter, which FacultyProfile to fetch.
   */
  where: Prisma.FacultyProfileWhereUniqueInput
}

/**
 * FacultyProfile findFirst
 */
export type FacultyProfileFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FacultyProfile
   */
  select?: Prisma.FacultyProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FacultyProfile
   */
  omit?: Prisma.FacultyProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FacultyProfileInclude<ExtArgs> | null
  /**
   * Filter, which FacultyProfile to fetch.
   */
  where?: Prisma.FacultyProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FacultyProfiles to fetch.
   */
  orderBy?: Prisma.FacultyProfileOrderByWithRelationInput | Prisma.FacultyProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FacultyProfiles.
   */
  cursor?: Prisma.FacultyProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FacultyProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FacultyProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FacultyProfiles.
   */
  distinct?: Prisma.FacultyProfileScalarFieldEnum | Prisma.FacultyProfileScalarFieldEnum[]
}

/**
 * FacultyProfile findFirstOrThrow
 */
export type FacultyProfileFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FacultyProfile
   */
  select?: Prisma.FacultyProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FacultyProfile
   */
  omit?: Prisma.FacultyProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FacultyProfileInclude<ExtArgs> | null
  /**
   * Filter, which FacultyProfile to fetch.
   */
  where?: Prisma.FacultyProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FacultyProfiles to fetch.
   */
  orderBy?: Prisma.FacultyProfileOrderByWithRelationInput | Prisma.FacultyProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FacultyProfiles.
   */
  cursor?: Prisma.FacultyProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FacultyProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FacultyProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FacultyProfiles.
   */
  distinct?: Prisma.FacultyProfileScalarFieldEnum | Prisma.FacultyProfileScalarFieldEnum[]
}

/**
 * FacultyProfile findMany
 */
export type FacultyProfileFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FacultyProfile
   */
  select?: Prisma.FacultyProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FacultyProfile
   */
  omit?: Prisma.FacultyProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FacultyProfileInclude<ExtArgs> | null
  /**
   * Filter, which FacultyProfiles to fetch.
   */
  where?: Prisma.FacultyProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FacultyProfiles to fetch.
   */
  orderBy?: Prisma.FacultyProfileOrderByWithRelationInput | Prisma.FacultyProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FacultyProfiles.
   */
  cursor?: Prisma.FacultyProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FacultyProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FacultyProfiles.
   */
  skip?: number
  distinct?: Prisma.FacultyProfileScalarFieldEnum | Prisma.FacultyProfileScalarFieldEnum[]
}

/**
 * FacultyProfile create
 */
export type FacultyProfileCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FacultyProfile
   */
  select?: Prisma.FacultyProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FacultyProfile
   */
  omit?: Prisma.FacultyProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FacultyProfileInclude<ExtArgs> | null
  /**
   * The data needed to create a FacultyProfile.
   */
  data: Prisma.XOR<Prisma.FacultyProfileCreateInput, Prisma.FacultyProfileUncheckedCreateInput>
}

/**
 * FacultyProfile createMany
 */
export type FacultyProfileCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FacultyProfiles.
   */
  data: Prisma.FacultyProfileCreateManyInput | Prisma.FacultyProfileCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FacultyProfile createManyAndReturn
 */
export type FacultyProfileCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FacultyProfile
   */
  select?: Prisma.FacultyProfileSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FacultyProfile
   */
  omit?: Prisma.FacultyProfileOmit<ExtArgs> | null
  /**
   * The data used to create many FacultyProfiles.
   */
  data: Prisma.FacultyProfileCreateManyInput | Prisma.FacultyProfileCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FacultyProfileIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * FacultyProfile update
 */
export type FacultyProfileUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FacultyProfile
   */
  select?: Prisma.FacultyProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FacultyProfile
   */
  omit?: Prisma.FacultyProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FacultyProfileInclude<ExtArgs> | null
  /**
   * The data needed to update a FacultyProfile.
   */
  data: Prisma.XOR<Prisma.FacultyProfileUpdateInput, Prisma.FacultyProfileUncheckedUpdateInput>
  /**
   * Choose, which FacultyProfile to update.
   */
  where: Prisma.FacultyProfileWhereUniqueInput
}

/**
 * FacultyProfile updateMany
 */
export type FacultyProfileUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FacultyProfiles.
   */
  data: Prisma.XOR<Prisma.FacultyProfileUpdateManyMutationInput, Prisma.FacultyProfileUncheckedUpdateManyInput>
  /**
   * Filter which FacultyProfiles to update
   */
  where?: Prisma.FacultyProfileWhereInput
  /**
   * Limit how many FacultyProfiles to update.
   */
  limit?: number
}

/**
 * FacultyProfile updateManyAndReturn
 */
export type FacultyProfileUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FacultyProfile
   */
  select?: Prisma.FacultyProfileSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FacultyProfile
   */
  omit?: Prisma.FacultyProfileOmit<ExtArgs> | null
  /**
   * The data used to update FacultyProfiles.
   */
  data: Prisma.XOR<Prisma.FacultyProfileUpdateManyMutationInput, Prisma.FacultyProfileUncheckedUpdateManyInput>
  /**
   * Filter which FacultyProfiles to update
   */
  where?: Prisma.FacultyProfileWhereInput
  /**
   * Limit how many FacultyProfiles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FacultyProfileIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * FacultyProfile upsert
 */
export type FacultyProfileUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FacultyProfile
   */
  select?: Prisma.FacultyProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FacultyProfile
   */
  omit?: Prisma.FacultyProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FacultyProfileInclude<ExtArgs> | null
  /**
   * The filter to search for the FacultyProfile to update in case it exists.
   */
  where: Prisma.FacultyProfileWhereUniqueInput
  /**
   * In case the FacultyProfile found by the `where` argument doesn't exist, create a new FacultyProfile with this data.
   */
  create: Prisma.XOR<Prisma.FacultyProfileCreateInput, Prisma.FacultyProfileUncheckedCreateInput>
  /**
   * In case the FacultyProfile was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FacultyProfileUpdateInput, Prisma.FacultyProfileUncheckedUpdateInput>
}

/**
 * FacultyProfile delete
 */
export type FacultyProfileDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FacultyProfile
   */
  select?: Prisma.FacultyProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FacultyProfile
   */
  omit?: Prisma.FacultyProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FacultyProfileInclude<ExtArgs> | null
  /**
   * Filter which FacultyProfile to delete.
   */
  where: Prisma.FacultyProfileWhereUniqueInput
}

/**
 * FacultyProfile deleteMany
 */
export type FacultyProfileDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FacultyProfiles to delete
   */
  where?: Prisma.FacultyProfileWhereInput
  /**
   * Limit how many FacultyProfiles to delete.
   */
  limit?: number
}

/**
 * FacultyProfile.Project
 */
export type FacultyProfile$ProjectArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  where?: Prisma.ProjectWhereInput
  orderBy?: Prisma.ProjectOrderByWithRelationInput | Prisma.ProjectOrderByWithRelationInput[]
  cursor?: Prisma.ProjectWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProjectScalarFieldEnum | Prisma.ProjectScalarFieldEnum[]
}

/**
 * FacultyProfile without action
 */
export type FacultyProfileDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FacultyProfile
   */
  select?: Prisma.FacultyProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FacultyProfile
   */
  omit?: Prisma.FacultyProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FacultyProfileInclude<ExtArgs> | null
}
