
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MeetingAttendance` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MeetingAttendance
 * 
 */
export type MeetingAttendanceModel = runtime.Types.Result.DefaultSelection<Prisma.$MeetingAttendancePayload>

export type AggregateMeetingAttendance = {
  _count: MeetingAttendanceCountAggregateOutputType | null
  _min: MeetingAttendanceMinAggregateOutputType | null
  _max: MeetingAttendanceMaxAggregateOutputType | null
}

export type MeetingAttendanceMinAggregateOutputType = {
  id: string | null
  meetingId: string | null
  studentId: string | null
  isPresent: boolean | null
  remarks: string | null
}

export type MeetingAttendanceMaxAggregateOutputType = {
  id: string | null
  meetingId: string | null
  studentId: string | null
  isPresent: boolean | null
  remarks: string | null
}

export type MeetingAttendanceCountAggregateOutputType = {
  id: number
  meetingId: number
  studentId: number
  isPresent: number
  remarks: number
  _all: number
}


export type MeetingAttendanceMinAggregateInputType = {
  id?: true
  meetingId?: true
  studentId?: true
  isPresent?: true
  remarks?: true
}

export type MeetingAttendanceMaxAggregateInputType = {
  id?: true
  meetingId?: true
  studentId?: true
  isPresent?: true
  remarks?: true
}

export type MeetingAttendanceCountAggregateInputType = {
  id?: true
  meetingId?: true
  studentId?: true
  isPresent?: true
  remarks?: true
  _all?: true
}

export type MeetingAttendanceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MeetingAttendance to aggregate.
   */
  where?: Prisma.MeetingAttendanceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MeetingAttendances to fetch.
   */
  orderBy?: Prisma.MeetingAttendanceOrderByWithRelationInput | Prisma.MeetingAttendanceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MeetingAttendanceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MeetingAttendances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MeetingAttendances.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MeetingAttendances
  **/
  _count?: true | MeetingAttendanceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MeetingAttendanceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MeetingAttendanceMaxAggregateInputType
}

export type GetMeetingAttendanceAggregateType<T extends MeetingAttendanceAggregateArgs> = {
      [P in keyof T & keyof AggregateMeetingAttendance]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMeetingAttendance[P]>
    : Prisma.GetScalarType<T[P], AggregateMeetingAttendance[P]>
}




export type MeetingAttendanceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MeetingAttendanceWhereInput
  orderBy?: Prisma.MeetingAttendanceOrderByWithAggregationInput | Prisma.MeetingAttendanceOrderByWithAggregationInput[]
  by: Prisma.MeetingAttendanceScalarFieldEnum[] | Prisma.MeetingAttendanceScalarFieldEnum
  having?: Prisma.MeetingAttendanceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MeetingAttendanceCountAggregateInputType | true
  _min?: MeetingAttendanceMinAggregateInputType
  _max?: MeetingAttendanceMaxAggregateInputType
}

export type MeetingAttendanceGroupByOutputType = {
  id: string
  meetingId: string
  studentId: string
  isPresent: boolean
  remarks: string | null
  _count: MeetingAttendanceCountAggregateOutputType | null
  _min: MeetingAttendanceMinAggregateOutputType | null
  _max: MeetingAttendanceMaxAggregateOutputType | null
}

type GetMeetingAttendanceGroupByPayload<T extends MeetingAttendanceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MeetingAttendanceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MeetingAttendanceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MeetingAttendanceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MeetingAttendanceGroupByOutputType[P]>
      }
    >
  >



export type MeetingAttendanceWhereInput = {
  AND?: Prisma.MeetingAttendanceWhereInput | Prisma.MeetingAttendanceWhereInput[]
  OR?: Prisma.MeetingAttendanceWhereInput[]
  NOT?: Prisma.MeetingAttendanceWhereInput | Prisma.MeetingAttendanceWhereInput[]
  id?: Prisma.StringFilter<"MeetingAttendance"> | string
  meetingId?: Prisma.StringFilter<"MeetingAttendance"> | string
  studentId?: Prisma.StringFilter<"MeetingAttendance"> | string
  isPresent?: Prisma.BoolFilter<"MeetingAttendance"> | boolean
  remarks?: Prisma.StringNullableFilter<"MeetingAttendance"> | string | null
  Meeting?: Prisma.XOR<Prisma.MeetingScalarRelationFilter, Prisma.MeetingWhereInput>
  Student?: Prisma.XOR<Prisma.StudentProfileScalarRelationFilter, Prisma.StudentProfileWhereInput>
}

export type MeetingAttendanceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  meetingId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  isPresent?: Prisma.SortOrder
  remarks?: Prisma.SortOrderInput | Prisma.SortOrder
  Meeting?: Prisma.MeetingOrderByWithRelationInput
  Student?: Prisma.StudentProfileOrderByWithRelationInput
}

export type MeetingAttendanceWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.MeetingAttendanceWhereInput | Prisma.MeetingAttendanceWhereInput[]
  OR?: Prisma.MeetingAttendanceWhereInput[]
  NOT?: Prisma.MeetingAttendanceWhereInput | Prisma.MeetingAttendanceWhereInput[]
  meetingId?: Prisma.StringFilter<"MeetingAttendance"> | string
  studentId?: Prisma.StringFilter<"MeetingAttendance"> | string
  isPresent?: Prisma.BoolFilter<"MeetingAttendance"> | boolean
  remarks?: Prisma.StringNullableFilter<"MeetingAttendance"> | string | null
  Meeting?: Prisma.XOR<Prisma.MeetingScalarRelationFilter, Prisma.MeetingWhereInput>
  Student?: Prisma.XOR<Prisma.StudentProfileScalarRelationFilter, Prisma.StudentProfileWhereInput>
}, "id">

export type MeetingAttendanceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  meetingId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  isPresent?: Prisma.SortOrder
  remarks?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.MeetingAttendanceCountOrderByAggregateInput
  _max?: Prisma.MeetingAttendanceMaxOrderByAggregateInput
  _min?: Prisma.MeetingAttendanceMinOrderByAggregateInput
}

export type MeetingAttendanceScalarWhereWithAggregatesInput = {
  AND?: Prisma.MeetingAttendanceScalarWhereWithAggregatesInput | Prisma.MeetingAttendanceScalarWhereWithAggregatesInput[]
  OR?: Prisma.MeetingAttendanceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MeetingAttendanceScalarWhereWithAggregatesInput | Prisma.MeetingAttendanceScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"MeetingAttendance"> | string
  meetingId?: Prisma.StringWithAggregatesFilter<"MeetingAttendance"> | string
  studentId?: Prisma.StringWithAggregatesFilter<"MeetingAttendance"> | string
  isPresent?: Prisma.BoolWithAggregatesFilter<"MeetingAttendance"> | boolean
  remarks?: Prisma.StringNullableWithAggregatesFilter<"MeetingAttendance"> | string | null
}

export type MeetingAttendanceCreateInput = {
  id?: string
  isPresent?: boolean
  remarks?: string | null
  Meeting: Prisma.MeetingCreateNestedOneWithoutAttendanceInput
  Student: Prisma.StudentProfileCreateNestedOneWithoutAttendanceInput
}

export type MeetingAttendanceUncheckedCreateInput = {
  id?: string
  meetingId: string
  studentId: string
  isPresent?: boolean
  remarks?: string | null
}

export type MeetingAttendanceUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isPresent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Meeting?: Prisma.MeetingUpdateOneRequiredWithoutAttendanceNestedInput
  Student?: Prisma.StudentProfileUpdateOneRequiredWithoutAttendanceNestedInput
}

export type MeetingAttendanceUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  meetingId?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  isPresent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MeetingAttendanceCreateManyInput = {
  id?: string
  meetingId: string
  studentId: string
  isPresent?: boolean
  remarks?: string | null
}

export type MeetingAttendanceUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isPresent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MeetingAttendanceUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  meetingId?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  isPresent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MeetingAttendanceListRelationFilter = {
  every?: Prisma.MeetingAttendanceWhereInput
  some?: Prisma.MeetingAttendanceWhereInput
  none?: Prisma.MeetingAttendanceWhereInput
}

export type MeetingAttendanceOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MeetingAttendanceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  meetingId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  isPresent?: Prisma.SortOrder
  remarks?: Prisma.SortOrder
}

export type MeetingAttendanceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  meetingId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  isPresent?: Prisma.SortOrder
  remarks?: Prisma.SortOrder
}

export type MeetingAttendanceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  meetingId?: Prisma.SortOrder
  studentId?: Prisma.SortOrder
  isPresent?: Prisma.SortOrder
  remarks?: Prisma.SortOrder
}

export type MeetingAttendanceCreateNestedManyWithoutMeetingInput = {
  create?: Prisma.XOR<Prisma.MeetingAttendanceCreateWithoutMeetingInput, Prisma.MeetingAttendanceUncheckedCreateWithoutMeetingInput> | Prisma.MeetingAttendanceCreateWithoutMeetingInput[] | Prisma.MeetingAttendanceUncheckedCreateWithoutMeetingInput[]
  connectOrCreate?: Prisma.MeetingAttendanceCreateOrConnectWithoutMeetingInput | Prisma.MeetingAttendanceCreateOrConnectWithoutMeetingInput[]
  createMany?: Prisma.MeetingAttendanceCreateManyMeetingInputEnvelope
  connect?: Prisma.MeetingAttendanceWhereUniqueInput | Prisma.MeetingAttendanceWhereUniqueInput[]
}

export type MeetingAttendanceUncheckedCreateNestedManyWithoutMeetingInput = {
  create?: Prisma.XOR<Prisma.MeetingAttendanceCreateWithoutMeetingInput, Prisma.MeetingAttendanceUncheckedCreateWithoutMeetingInput> | Prisma.MeetingAttendanceCreateWithoutMeetingInput[] | Prisma.MeetingAttendanceUncheckedCreateWithoutMeetingInput[]
  connectOrCreate?: Prisma.MeetingAttendanceCreateOrConnectWithoutMeetingInput | Prisma.MeetingAttendanceCreateOrConnectWithoutMeetingInput[]
  createMany?: Prisma.MeetingAttendanceCreateManyMeetingInputEnvelope
  connect?: Prisma.MeetingAttendanceWhereUniqueInput | Prisma.MeetingAttendanceWhereUniqueInput[]
}

export type MeetingAttendanceUpdateManyWithoutMeetingNestedInput = {
  create?: Prisma.XOR<Prisma.MeetingAttendanceCreateWithoutMeetingInput, Prisma.MeetingAttendanceUncheckedCreateWithoutMeetingInput> | Prisma.MeetingAttendanceCreateWithoutMeetingInput[] | Prisma.MeetingAttendanceUncheckedCreateWithoutMeetingInput[]
  connectOrCreate?: Prisma.MeetingAttendanceCreateOrConnectWithoutMeetingInput | Prisma.MeetingAttendanceCreateOrConnectWithoutMeetingInput[]
  upsert?: Prisma.MeetingAttendanceUpsertWithWhereUniqueWithoutMeetingInput | Prisma.MeetingAttendanceUpsertWithWhereUniqueWithoutMeetingInput[]
  createMany?: Prisma.MeetingAttendanceCreateManyMeetingInputEnvelope
  set?: Prisma.MeetingAttendanceWhereUniqueInput | Prisma.MeetingAttendanceWhereUniqueInput[]
  disconnect?: Prisma.MeetingAttendanceWhereUniqueInput | Prisma.MeetingAttendanceWhereUniqueInput[]
  delete?: Prisma.MeetingAttendanceWhereUniqueInput | Prisma.MeetingAttendanceWhereUniqueInput[]
  connect?: Prisma.MeetingAttendanceWhereUniqueInput | Prisma.MeetingAttendanceWhereUniqueInput[]
  update?: Prisma.MeetingAttendanceUpdateWithWhereUniqueWithoutMeetingInput | Prisma.MeetingAttendanceUpdateWithWhereUniqueWithoutMeetingInput[]
  updateMany?: Prisma.MeetingAttendanceUpdateManyWithWhereWithoutMeetingInput | Prisma.MeetingAttendanceUpdateManyWithWhereWithoutMeetingInput[]
  deleteMany?: Prisma.MeetingAttendanceScalarWhereInput | Prisma.MeetingAttendanceScalarWhereInput[]
}

export type MeetingAttendanceUncheckedUpdateManyWithoutMeetingNestedInput = {
  create?: Prisma.XOR<Prisma.MeetingAttendanceCreateWithoutMeetingInput, Prisma.MeetingAttendanceUncheckedCreateWithoutMeetingInput> | Prisma.MeetingAttendanceCreateWithoutMeetingInput[] | Prisma.MeetingAttendanceUncheckedCreateWithoutMeetingInput[]
  connectOrCreate?: Prisma.MeetingAttendanceCreateOrConnectWithoutMeetingInput | Prisma.MeetingAttendanceCreateOrConnectWithoutMeetingInput[]
  upsert?: Prisma.MeetingAttendanceUpsertWithWhereUniqueWithoutMeetingInput | Prisma.MeetingAttendanceUpsertWithWhereUniqueWithoutMeetingInput[]
  createMany?: Prisma.MeetingAttendanceCreateManyMeetingInputEnvelope
  set?: Prisma.MeetingAttendanceWhereUniqueInput | Prisma.MeetingAttendanceWhereUniqueInput[]
  disconnect?: Prisma.MeetingAttendanceWhereUniqueInput | Prisma.MeetingAttendanceWhereUniqueInput[]
  delete?: Prisma.MeetingAttendanceWhereUniqueInput | Prisma.MeetingAttendanceWhereUniqueInput[]
  connect?: Prisma.MeetingAttendanceWhereUniqueInput | Prisma.MeetingAttendanceWhereUniqueInput[]
  update?: Prisma.MeetingAttendanceUpdateWithWhereUniqueWithoutMeetingInput | Prisma.MeetingAttendanceUpdateWithWhereUniqueWithoutMeetingInput[]
  updateMany?: Prisma.MeetingAttendanceUpdateManyWithWhereWithoutMeetingInput | Prisma.MeetingAttendanceUpdateManyWithWhereWithoutMeetingInput[]
  deleteMany?: Prisma.MeetingAttendanceScalarWhereInput | Prisma.MeetingAttendanceScalarWhereInput[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type MeetingAttendanceCreateNestedManyWithoutStudentInput = {
  create?: Prisma.XOR<Prisma.MeetingAttendanceCreateWithoutStudentInput, Prisma.MeetingAttendanceUncheckedCreateWithoutStudentInput> | Prisma.MeetingAttendanceCreateWithoutStudentInput[] | Prisma.MeetingAttendanceUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.MeetingAttendanceCreateOrConnectWithoutStudentInput | Prisma.MeetingAttendanceCreateOrConnectWithoutStudentInput[]
  createMany?: Prisma.MeetingAttendanceCreateManyStudentInputEnvelope
  connect?: Prisma.MeetingAttendanceWhereUniqueInput | Prisma.MeetingAttendanceWhereUniqueInput[]
}

export type MeetingAttendanceUncheckedCreateNestedManyWithoutStudentInput = {
  create?: Prisma.XOR<Prisma.MeetingAttendanceCreateWithoutStudentInput, Prisma.MeetingAttendanceUncheckedCreateWithoutStudentInput> | Prisma.MeetingAttendanceCreateWithoutStudentInput[] | Prisma.MeetingAttendanceUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.MeetingAttendanceCreateOrConnectWithoutStudentInput | Prisma.MeetingAttendanceCreateOrConnectWithoutStudentInput[]
  createMany?: Prisma.MeetingAttendanceCreateManyStudentInputEnvelope
  connect?: Prisma.MeetingAttendanceWhereUniqueInput | Prisma.MeetingAttendanceWhereUniqueInput[]
}

export type MeetingAttendanceUpdateManyWithoutStudentNestedInput = {
  create?: Prisma.XOR<Prisma.MeetingAttendanceCreateWithoutStudentInput, Prisma.MeetingAttendanceUncheckedCreateWithoutStudentInput> | Prisma.MeetingAttendanceCreateWithoutStudentInput[] | Prisma.MeetingAttendanceUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.MeetingAttendanceCreateOrConnectWithoutStudentInput | Prisma.MeetingAttendanceCreateOrConnectWithoutStudentInput[]
  upsert?: Prisma.MeetingAttendanceUpsertWithWhereUniqueWithoutStudentInput | Prisma.MeetingAttendanceUpsertWithWhereUniqueWithoutStudentInput[]
  createMany?: Prisma.MeetingAttendanceCreateManyStudentInputEnvelope
  set?: Prisma.MeetingAttendanceWhereUniqueInput | Prisma.MeetingAttendanceWhereUniqueInput[]
  disconnect?: Prisma.MeetingAttendanceWhereUniqueInput | Prisma.MeetingAttendanceWhereUniqueInput[]
  delete?: Prisma.MeetingAttendanceWhereUniqueInput | Prisma.MeetingAttendanceWhereUniqueInput[]
  connect?: Prisma.MeetingAttendanceWhereUniqueInput | Prisma.MeetingAttendanceWhereUniqueInput[]
  update?: Prisma.MeetingAttendanceUpdateWithWhereUniqueWithoutStudentInput | Prisma.MeetingAttendanceUpdateWithWhereUniqueWithoutStudentInput[]
  updateMany?: Prisma.MeetingAttendanceUpdateManyWithWhereWithoutStudentInput | Prisma.MeetingAttendanceUpdateManyWithWhereWithoutStudentInput[]
  deleteMany?: Prisma.MeetingAttendanceScalarWhereInput | Prisma.MeetingAttendanceScalarWhereInput[]
}

export type MeetingAttendanceUncheckedUpdateManyWithoutStudentNestedInput = {
  create?: Prisma.XOR<Prisma.MeetingAttendanceCreateWithoutStudentInput, Prisma.MeetingAttendanceUncheckedCreateWithoutStudentInput> | Prisma.MeetingAttendanceCreateWithoutStudentInput[] | Prisma.MeetingAttendanceUncheckedCreateWithoutStudentInput[]
  connectOrCreate?: Prisma.MeetingAttendanceCreateOrConnectWithoutStudentInput | Prisma.MeetingAttendanceCreateOrConnectWithoutStudentInput[]
  upsert?: Prisma.MeetingAttendanceUpsertWithWhereUniqueWithoutStudentInput | Prisma.MeetingAttendanceUpsertWithWhereUniqueWithoutStudentInput[]
  createMany?: Prisma.MeetingAttendanceCreateManyStudentInputEnvelope
  set?: Prisma.MeetingAttendanceWhereUniqueInput | Prisma.MeetingAttendanceWhereUniqueInput[]
  disconnect?: Prisma.MeetingAttendanceWhereUniqueInput | Prisma.MeetingAttendanceWhereUniqueInput[]
  delete?: Prisma.MeetingAttendanceWhereUniqueInput | Prisma.MeetingAttendanceWhereUniqueInput[]
  connect?: Prisma.MeetingAttendanceWhereUniqueInput | Prisma.MeetingAttendanceWhereUniqueInput[]
  update?: Prisma.MeetingAttendanceUpdateWithWhereUniqueWithoutStudentInput | Prisma.MeetingAttendanceUpdateWithWhereUniqueWithoutStudentInput[]
  updateMany?: Prisma.MeetingAttendanceUpdateManyWithWhereWithoutStudentInput | Prisma.MeetingAttendanceUpdateManyWithWhereWithoutStudentInput[]
  deleteMany?: Prisma.MeetingAttendanceScalarWhereInput | Prisma.MeetingAttendanceScalarWhereInput[]
}

export type MeetingAttendanceCreateWithoutMeetingInput = {
  id?: string
  isPresent?: boolean
  remarks?: string | null
  Student: Prisma.StudentProfileCreateNestedOneWithoutAttendanceInput
}

export type MeetingAttendanceUncheckedCreateWithoutMeetingInput = {
  id?: string
  studentId: string
  isPresent?: boolean
  remarks?: string | null
}

export type MeetingAttendanceCreateOrConnectWithoutMeetingInput = {
  where: Prisma.MeetingAttendanceWhereUniqueInput
  create: Prisma.XOR<Prisma.MeetingAttendanceCreateWithoutMeetingInput, Prisma.MeetingAttendanceUncheckedCreateWithoutMeetingInput>
}

export type MeetingAttendanceCreateManyMeetingInputEnvelope = {
  data: Prisma.MeetingAttendanceCreateManyMeetingInput | Prisma.MeetingAttendanceCreateManyMeetingInput[]
  skipDuplicates?: boolean
}

export type MeetingAttendanceUpsertWithWhereUniqueWithoutMeetingInput = {
  where: Prisma.MeetingAttendanceWhereUniqueInput
  update: Prisma.XOR<Prisma.MeetingAttendanceUpdateWithoutMeetingInput, Prisma.MeetingAttendanceUncheckedUpdateWithoutMeetingInput>
  create: Prisma.XOR<Prisma.MeetingAttendanceCreateWithoutMeetingInput, Prisma.MeetingAttendanceUncheckedCreateWithoutMeetingInput>
}

export type MeetingAttendanceUpdateWithWhereUniqueWithoutMeetingInput = {
  where: Prisma.MeetingAttendanceWhereUniqueInput
  data: Prisma.XOR<Prisma.MeetingAttendanceUpdateWithoutMeetingInput, Prisma.MeetingAttendanceUncheckedUpdateWithoutMeetingInput>
}

export type MeetingAttendanceUpdateManyWithWhereWithoutMeetingInput = {
  where: Prisma.MeetingAttendanceScalarWhereInput
  data: Prisma.XOR<Prisma.MeetingAttendanceUpdateManyMutationInput, Prisma.MeetingAttendanceUncheckedUpdateManyWithoutMeetingInput>
}

export type MeetingAttendanceScalarWhereInput = {
  AND?: Prisma.MeetingAttendanceScalarWhereInput | Prisma.MeetingAttendanceScalarWhereInput[]
  OR?: Prisma.MeetingAttendanceScalarWhereInput[]
  NOT?: Prisma.MeetingAttendanceScalarWhereInput | Prisma.MeetingAttendanceScalarWhereInput[]
  id?: Prisma.StringFilter<"MeetingAttendance"> | string
  meetingId?: Prisma.StringFilter<"MeetingAttendance"> | string
  studentId?: Prisma.StringFilter<"MeetingAttendance"> | string
  isPresent?: Prisma.BoolFilter<"MeetingAttendance"> | boolean
  remarks?: Prisma.StringNullableFilter<"MeetingAttendance"> | string | null
}

export type MeetingAttendanceCreateWithoutStudentInput = {
  id?: string
  isPresent?: boolean
  remarks?: string | null
  Meeting: Prisma.MeetingCreateNestedOneWithoutAttendanceInput
}

export type MeetingAttendanceUncheckedCreateWithoutStudentInput = {
  id?: string
  meetingId: string
  isPresent?: boolean
  remarks?: string | null
}

export type MeetingAttendanceCreateOrConnectWithoutStudentInput = {
  where: Prisma.MeetingAttendanceWhereUniqueInput
  create: Prisma.XOR<Prisma.MeetingAttendanceCreateWithoutStudentInput, Prisma.MeetingAttendanceUncheckedCreateWithoutStudentInput>
}

export type MeetingAttendanceCreateManyStudentInputEnvelope = {
  data: Prisma.MeetingAttendanceCreateManyStudentInput | Prisma.MeetingAttendanceCreateManyStudentInput[]
  skipDuplicates?: boolean
}

export type MeetingAttendanceUpsertWithWhereUniqueWithoutStudentInput = {
  where: Prisma.MeetingAttendanceWhereUniqueInput
  update: Prisma.XOR<Prisma.MeetingAttendanceUpdateWithoutStudentInput, Prisma.MeetingAttendanceUncheckedUpdateWithoutStudentInput>
  create: Prisma.XOR<Prisma.MeetingAttendanceCreateWithoutStudentInput, Prisma.MeetingAttendanceUncheckedCreateWithoutStudentInput>
}

export type MeetingAttendanceUpdateWithWhereUniqueWithoutStudentInput = {
  where: Prisma.MeetingAttendanceWhereUniqueInput
  data: Prisma.XOR<Prisma.MeetingAttendanceUpdateWithoutStudentInput, Prisma.MeetingAttendanceUncheckedUpdateWithoutStudentInput>
}

export type MeetingAttendanceUpdateManyWithWhereWithoutStudentInput = {
  where: Prisma.MeetingAttendanceScalarWhereInput
  data: Prisma.XOR<Prisma.MeetingAttendanceUpdateManyMutationInput, Prisma.MeetingAttendanceUncheckedUpdateManyWithoutStudentInput>
}

export type MeetingAttendanceCreateManyMeetingInput = {
  id?: string
  studentId: string
  isPresent?: boolean
  remarks?: string | null
}

export type MeetingAttendanceUpdateWithoutMeetingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isPresent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Student?: Prisma.StudentProfileUpdateOneRequiredWithoutAttendanceNestedInput
}

export type MeetingAttendanceUncheckedUpdateWithoutMeetingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  isPresent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MeetingAttendanceUncheckedUpdateManyWithoutMeetingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  studentId?: Prisma.StringFieldUpdateOperationsInput | string
  isPresent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MeetingAttendanceCreateManyStudentInput = {
  id?: string
  meetingId: string
  isPresent?: boolean
  remarks?: string | null
}

export type MeetingAttendanceUpdateWithoutStudentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  isPresent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Meeting?: Prisma.MeetingUpdateOneRequiredWithoutAttendanceNestedInput
}

export type MeetingAttendanceUncheckedUpdateWithoutStudentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  meetingId?: Prisma.StringFieldUpdateOperationsInput | string
  isPresent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MeetingAttendanceUncheckedUpdateManyWithoutStudentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  meetingId?: Prisma.StringFieldUpdateOperationsInput | string
  isPresent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remarks?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type MeetingAttendanceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  meetingId?: boolean
  studentId?: boolean
  isPresent?: boolean
  remarks?: boolean
  Meeting?: boolean | Prisma.MeetingDefaultArgs<ExtArgs>
  Student?: boolean | Prisma.StudentProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["meetingAttendance"]>

export type MeetingAttendanceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  meetingId?: boolean
  studentId?: boolean
  isPresent?: boolean
  remarks?: boolean
  Meeting?: boolean | Prisma.MeetingDefaultArgs<ExtArgs>
  Student?: boolean | Prisma.StudentProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["meetingAttendance"]>

export type MeetingAttendanceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  meetingId?: boolean
  studentId?: boolean
  isPresent?: boolean
  remarks?: boolean
  Meeting?: boolean | Prisma.MeetingDefaultArgs<ExtArgs>
  Student?: boolean | Prisma.StudentProfileDefaultArgs<ExtArgs>
}, ExtArgs["result"]["meetingAttendance"]>

export type MeetingAttendanceSelectScalar = {
  id?: boolean
  meetingId?: boolean
  studentId?: boolean
  isPresent?: boolean
  remarks?: boolean
}

export type MeetingAttendanceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "meetingId" | "studentId" | "isPresent" | "remarks", ExtArgs["result"]["meetingAttendance"]>
export type MeetingAttendanceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Meeting?: boolean | Prisma.MeetingDefaultArgs<ExtArgs>
  Student?: boolean | Prisma.StudentProfileDefaultArgs<ExtArgs>
}
export type MeetingAttendanceIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Meeting?: boolean | Prisma.MeetingDefaultArgs<ExtArgs>
  Student?: boolean | Prisma.StudentProfileDefaultArgs<ExtArgs>
}
export type MeetingAttendanceIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Meeting?: boolean | Prisma.MeetingDefaultArgs<ExtArgs>
  Student?: boolean | Prisma.StudentProfileDefaultArgs<ExtArgs>
}

export type $MeetingAttendancePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MeetingAttendance"
  objects: {
    Meeting: Prisma.$MeetingPayload<ExtArgs>
    Student: Prisma.$StudentProfilePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    meetingId: string
    studentId: string
    isPresent: boolean
    remarks: string | null
  }, ExtArgs["result"]["meetingAttendance"]>
  composites: {}
}

export type MeetingAttendanceGetPayload<S extends boolean | null | undefined | MeetingAttendanceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MeetingAttendancePayload, S>

export type MeetingAttendanceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MeetingAttendanceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MeetingAttendanceCountAggregateInputType | true
  }

export interface MeetingAttendanceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MeetingAttendance'], meta: { name: 'MeetingAttendance' } }
  /**
   * Find zero or one MeetingAttendance that matches the filter.
   * @param {MeetingAttendanceFindUniqueArgs} args - Arguments to find a MeetingAttendance
   * @example
   * // Get one MeetingAttendance
   * const meetingAttendance = await prisma.meetingAttendance.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MeetingAttendanceFindUniqueArgs>(args: Prisma.SelectSubset<T, MeetingAttendanceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MeetingAttendanceClient<runtime.Types.Result.GetResult<Prisma.$MeetingAttendancePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MeetingAttendance that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MeetingAttendanceFindUniqueOrThrowArgs} args - Arguments to find a MeetingAttendance
   * @example
   * // Get one MeetingAttendance
   * const meetingAttendance = await prisma.meetingAttendance.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MeetingAttendanceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MeetingAttendanceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MeetingAttendanceClient<runtime.Types.Result.GetResult<Prisma.$MeetingAttendancePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MeetingAttendance that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MeetingAttendanceFindFirstArgs} args - Arguments to find a MeetingAttendance
   * @example
   * // Get one MeetingAttendance
   * const meetingAttendance = await prisma.meetingAttendance.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MeetingAttendanceFindFirstArgs>(args?: Prisma.SelectSubset<T, MeetingAttendanceFindFirstArgs<ExtArgs>>): Prisma.Prisma__MeetingAttendanceClient<runtime.Types.Result.GetResult<Prisma.$MeetingAttendancePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MeetingAttendance that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MeetingAttendanceFindFirstOrThrowArgs} args - Arguments to find a MeetingAttendance
   * @example
   * // Get one MeetingAttendance
   * const meetingAttendance = await prisma.meetingAttendance.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MeetingAttendanceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MeetingAttendanceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MeetingAttendanceClient<runtime.Types.Result.GetResult<Prisma.$MeetingAttendancePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MeetingAttendances that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MeetingAttendanceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MeetingAttendances
   * const meetingAttendances = await prisma.meetingAttendance.findMany()
   * 
   * // Get first 10 MeetingAttendances
   * const meetingAttendances = await prisma.meetingAttendance.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const meetingAttendanceWithIdOnly = await prisma.meetingAttendance.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MeetingAttendanceFindManyArgs>(args?: Prisma.SelectSubset<T, MeetingAttendanceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MeetingAttendancePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MeetingAttendance.
   * @param {MeetingAttendanceCreateArgs} args - Arguments to create a MeetingAttendance.
   * @example
   * // Create one MeetingAttendance
   * const MeetingAttendance = await prisma.meetingAttendance.create({
   *   data: {
   *     // ... data to create a MeetingAttendance
   *   }
   * })
   * 
   */
  create<T extends MeetingAttendanceCreateArgs>(args: Prisma.SelectSubset<T, MeetingAttendanceCreateArgs<ExtArgs>>): Prisma.Prisma__MeetingAttendanceClient<runtime.Types.Result.GetResult<Prisma.$MeetingAttendancePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MeetingAttendances.
   * @param {MeetingAttendanceCreateManyArgs} args - Arguments to create many MeetingAttendances.
   * @example
   * // Create many MeetingAttendances
   * const meetingAttendance = await prisma.meetingAttendance.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MeetingAttendanceCreateManyArgs>(args?: Prisma.SelectSubset<T, MeetingAttendanceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MeetingAttendances and returns the data saved in the database.
   * @param {MeetingAttendanceCreateManyAndReturnArgs} args - Arguments to create many MeetingAttendances.
   * @example
   * // Create many MeetingAttendances
   * const meetingAttendance = await prisma.meetingAttendance.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MeetingAttendances and only return the `id`
   * const meetingAttendanceWithIdOnly = await prisma.meetingAttendance.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MeetingAttendanceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MeetingAttendanceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MeetingAttendancePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MeetingAttendance.
   * @param {MeetingAttendanceDeleteArgs} args - Arguments to delete one MeetingAttendance.
   * @example
   * // Delete one MeetingAttendance
   * const MeetingAttendance = await prisma.meetingAttendance.delete({
   *   where: {
   *     // ... filter to delete one MeetingAttendance
   *   }
   * })
   * 
   */
  delete<T extends MeetingAttendanceDeleteArgs>(args: Prisma.SelectSubset<T, MeetingAttendanceDeleteArgs<ExtArgs>>): Prisma.Prisma__MeetingAttendanceClient<runtime.Types.Result.GetResult<Prisma.$MeetingAttendancePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MeetingAttendance.
   * @param {MeetingAttendanceUpdateArgs} args - Arguments to update one MeetingAttendance.
   * @example
   * // Update one MeetingAttendance
   * const meetingAttendance = await prisma.meetingAttendance.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MeetingAttendanceUpdateArgs>(args: Prisma.SelectSubset<T, MeetingAttendanceUpdateArgs<ExtArgs>>): Prisma.Prisma__MeetingAttendanceClient<runtime.Types.Result.GetResult<Prisma.$MeetingAttendancePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MeetingAttendances.
   * @param {MeetingAttendanceDeleteManyArgs} args - Arguments to filter MeetingAttendances to delete.
   * @example
   * // Delete a few MeetingAttendances
   * const { count } = await prisma.meetingAttendance.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MeetingAttendanceDeleteManyArgs>(args?: Prisma.SelectSubset<T, MeetingAttendanceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MeetingAttendances.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MeetingAttendanceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MeetingAttendances
   * const meetingAttendance = await prisma.meetingAttendance.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MeetingAttendanceUpdateManyArgs>(args: Prisma.SelectSubset<T, MeetingAttendanceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MeetingAttendances and returns the data updated in the database.
   * @param {MeetingAttendanceUpdateManyAndReturnArgs} args - Arguments to update many MeetingAttendances.
   * @example
   * // Update many MeetingAttendances
   * const meetingAttendance = await prisma.meetingAttendance.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MeetingAttendances and only return the `id`
   * const meetingAttendanceWithIdOnly = await prisma.meetingAttendance.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MeetingAttendanceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MeetingAttendanceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MeetingAttendancePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MeetingAttendance.
   * @param {MeetingAttendanceUpsertArgs} args - Arguments to update or create a MeetingAttendance.
   * @example
   * // Update or create a MeetingAttendance
   * const meetingAttendance = await prisma.meetingAttendance.upsert({
   *   create: {
   *     // ... data to create a MeetingAttendance
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MeetingAttendance we want to update
   *   }
   * })
   */
  upsert<T extends MeetingAttendanceUpsertArgs>(args: Prisma.SelectSubset<T, MeetingAttendanceUpsertArgs<ExtArgs>>): Prisma.Prisma__MeetingAttendanceClient<runtime.Types.Result.GetResult<Prisma.$MeetingAttendancePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MeetingAttendances.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MeetingAttendanceCountArgs} args - Arguments to filter MeetingAttendances to count.
   * @example
   * // Count the number of MeetingAttendances
   * const count = await prisma.meetingAttendance.count({
   *   where: {
   *     // ... the filter for the MeetingAttendances we want to count
   *   }
   * })
  **/
  count<T extends MeetingAttendanceCountArgs>(
    args?: Prisma.Subset<T, MeetingAttendanceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MeetingAttendanceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MeetingAttendance.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MeetingAttendanceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MeetingAttendanceAggregateArgs>(args: Prisma.Subset<T, MeetingAttendanceAggregateArgs>): Prisma.PrismaPromise<GetMeetingAttendanceAggregateType<T>>

  /**
   * Group by MeetingAttendance.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MeetingAttendanceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MeetingAttendanceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MeetingAttendanceGroupByArgs['orderBy'] }
      : { orderBy?: MeetingAttendanceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MeetingAttendanceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMeetingAttendanceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MeetingAttendance model
 */
readonly fields: MeetingAttendanceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MeetingAttendance.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MeetingAttendanceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Meeting<T extends Prisma.MeetingDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MeetingDefaultArgs<ExtArgs>>): Prisma.Prisma__MeetingClient<runtime.Types.Result.GetResult<Prisma.$MeetingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  Student<T extends Prisma.StudentProfileDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StudentProfileDefaultArgs<ExtArgs>>): Prisma.Prisma__StudentProfileClient<runtime.Types.Result.GetResult<Prisma.$StudentProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MeetingAttendance model
 */
export interface MeetingAttendanceFieldRefs {
  readonly id: Prisma.FieldRef<"MeetingAttendance", 'String'>
  readonly meetingId: Prisma.FieldRef<"MeetingAttendance", 'String'>
  readonly studentId: Prisma.FieldRef<"MeetingAttendance", 'String'>
  readonly isPresent: Prisma.FieldRef<"MeetingAttendance", 'Boolean'>
  readonly remarks: Prisma.FieldRef<"MeetingAttendance", 'String'>
}
    

// Custom InputTypes
/**
 * MeetingAttendance findUnique
 */
export type MeetingAttendanceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeetingAttendance
   */
  select?: Prisma.MeetingAttendanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MeetingAttendance
   */
  omit?: Prisma.MeetingAttendanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MeetingAttendanceInclude<ExtArgs> | null
  /**
   * Filter, which MeetingAttendance to fetch.
   */
  where: Prisma.MeetingAttendanceWhereUniqueInput
}

/**
 * MeetingAttendance findUniqueOrThrow
 */
export type MeetingAttendanceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeetingAttendance
   */
  select?: Prisma.MeetingAttendanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MeetingAttendance
   */
  omit?: Prisma.MeetingAttendanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MeetingAttendanceInclude<ExtArgs> | null
  /**
   * Filter, which MeetingAttendance to fetch.
   */
  where: Prisma.MeetingAttendanceWhereUniqueInput
}

/**
 * MeetingAttendance findFirst
 */
export type MeetingAttendanceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeetingAttendance
   */
  select?: Prisma.MeetingAttendanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MeetingAttendance
   */
  omit?: Prisma.MeetingAttendanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MeetingAttendanceInclude<ExtArgs> | null
  /**
   * Filter, which MeetingAttendance to fetch.
   */
  where?: Prisma.MeetingAttendanceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MeetingAttendances to fetch.
   */
  orderBy?: Prisma.MeetingAttendanceOrderByWithRelationInput | Prisma.MeetingAttendanceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MeetingAttendances.
   */
  cursor?: Prisma.MeetingAttendanceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MeetingAttendances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MeetingAttendances.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MeetingAttendances.
   */
  distinct?: Prisma.MeetingAttendanceScalarFieldEnum | Prisma.MeetingAttendanceScalarFieldEnum[]
}

/**
 * MeetingAttendance findFirstOrThrow
 */
export type MeetingAttendanceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeetingAttendance
   */
  select?: Prisma.MeetingAttendanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MeetingAttendance
   */
  omit?: Prisma.MeetingAttendanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MeetingAttendanceInclude<ExtArgs> | null
  /**
   * Filter, which MeetingAttendance to fetch.
   */
  where?: Prisma.MeetingAttendanceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MeetingAttendances to fetch.
   */
  orderBy?: Prisma.MeetingAttendanceOrderByWithRelationInput | Prisma.MeetingAttendanceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MeetingAttendances.
   */
  cursor?: Prisma.MeetingAttendanceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MeetingAttendances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MeetingAttendances.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MeetingAttendances.
   */
  distinct?: Prisma.MeetingAttendanceScalarFieldEnum | Prisma.MeetingAttendanceScalarFieldEnum[]
}

/**
 * MeetingAttendance findMany
 */
export type MeetingAttendanceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeetingAttendance
   */
  select?: Prisma.MeetingAttendanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MeetingAttendance
   */
  omit?: Prisma.MeetingAttendanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MeetingAttendanceInclude<ExtArgs> | null
  /**
   * Filter, which MeetingAttendances to fetch.
   */
  where?: Prisma.MeetingAttendanceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MeetingAttendances to fetch.
   */
  orderBy?: Prisma.MeetingAttendanceOrderByWithRelationInput | Prisma.MeetingAttendanceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MeetingAttendances.
   */
  cursor?: Prisma.MeetingAttendanceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MeetingAttendances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MeetingAttendances.
   */
  skip?: number
  distinct?: Prisma.MeetingAttendanceScalarFieldEnum | Prisma.MeetingAttendanceScalarFieldEnum[]
}

/**
 * MeetingAttendance create
 */
export type MeetingAttendanceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeetingAttendance
   */
  select?: Prisma.MeetingAttendanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MeetingAttendance
   */
  omit?: Prisma.MeetingAttendanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MeetingAttendanceInclude<ExtArgs> | null
  /**
   * The data needed to create a MeetingAttendance.
   */
  data: Prisma.XOR<Prisma.MeetingAttendanceCreateInput, Prisma.MeetingAttendanceUncheckedCreateInput>
}

/**
 * MeetingAttendance createMany
 */
export type MeetingAttendanceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MeetingAttendances.
   */
  data: Prisma.MeetingAttendanceCreateManyInput | Prisma.MeetingAttendanceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MeetingAttendance createManyAndReturn
 */
export type MeetingAttendanceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeetingAttendance
   */
  select?: Prisma.MeetingAttendanceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MeetingAttendance
   */
  omit?: Prisma.MeetingAttendanceOmit<ExtArgs> | null
  /**
   * The data used to create many MeetingAttendances.
   */
  data: Prisma.MeetingAttendanceCreateManyInput | Prisma.MeetingAttendanceCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MeetingAttendanceIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * MeetingAttendance update
 */
export type MeetingAttendanceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeetingAttendance
   */
  select?: Prisma.MeetingAttendanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MeetingAttendance
   */
  omit?: Prisma.MeetingAttendanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MeetingAttendanceInclude<ExtArgs> | null
  /**
   * The data needed to update a MeetingAttendance.
   */
  data: Prisma.XOR<Prisma.MeetingAttendanceUpdateInput, Prisma.MeetingAttendanceUncheckedUpdateInput>
  /**
   * Choose, which MeetingAttendance to update.
   */
  where: Prisma.MeetingAttendanceWhereUniqueInput
}

/**
 * MeetingAttendance updateMany
 */
export type MeetingAttendanceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MeetingAttendances.
   */
  data: Prisma.XOR<Prisma.MeetingAttendanceUpdateManyMutationInput, Prisma.MeetingAttendanceUncheckedUpdateManyInput>
  /**
   * Filter which MeetingAttendances to update
   */
  where?: Prisma.MeetingAttendanceWhereInput
  /**
   * Limit how many MeetingAttendances to update.
   */
  limit?: number
}

/**
 * MeetingAttendance updateManyAndReturn
 */
export type MeetingAttendanceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeetingAttendance
   */
  select?: Prisma.MeetingAttendanceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MeetingAttendance
   */
  omit?: Prisma.MeetingAttendanceOmit<ExtArgs> | null
  /**
   * The data used to update MeetingAttendances.
   */
  data: Prisma.XOR<Prisma.MeetingAttendanceUpdateManyMutationInput, Prisma.MeetingAttendanceUncheckedUpdateManyInput>
  /**
   * Filter which MeetingAttendances to update
   */
  where?: Prisma.MeetingAttendanceWhereInput
  /**
   * Limit how many MeetingAttendances to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MeetingAttendanceIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * MeetingAttendance upsert
 */
export type MeetingAttendanceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeetingAttendance
   */
  select?: Prisma.MeetingAttendanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MeetingAttendance
   */
  omit?: Prisma.MeetingAttendanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MeetingAttendanceInclude<ExtArgs> | null
  /**
   * The filter to search for the MeetingAttendance to update in case it exists.
   */
  where: Prisma.MeetingAttendanceWhereUniqueInput
  /**
   * In case the MeetingAttendance found by the `where` argument doesn't exist, create a new MeetingAttendance with this data.
   */
  create: Prisma.XOR<Prisma.MeetingAttendanceCreateInput, Prisma.MeetingAttendanceUncheckedCreateInput>
  /**
   * In case the MeetingAttendance was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MeetingAttendanceUpdateInput, Prisma.MeetingAttendanceUncheckedUpdateInput>
}

/**
 * MeetingAttendance delete
 */
export type MeetingAttendanceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeetingAttendance
   */
  select?: Prisma.MeetingAttendanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MeetingAttendance
   */
  omit?: Prisma.MeetingAttendanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MeetingAttendanceInclude<ExtArgs> | null
  /**
   * Filter which MeetingAttendance to delete.
   */
  where: Prisma.MeetingAttendanceWhereUniqueInput
}

/**
 * MeetingAttendance deleteMany
 */
export type MeetingAttendanceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MeetingAttendances to delete
   */
  where?: Prisma.MeetingAttendanceWhereInput
  /**
   * Limit how many MeetingAttendances to delete.
   */
  limit?: number
}

/**
 * MeetingAttendance without action
 */
export type MeetingAttendanceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeetingAttendance
   */
  select?: Prisma.MeetingAttendanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MeetingAttendance
   */
  omit?: Prisma.MeetingAttendanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MeetingAttendanceInclude<ExtArgs> | null
}
