
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Project` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Project
 * 
 */
export type ProjectModel = runtime.Types.Result.DefaultSelection<Prisma.$ProjectPayload>

export type AggregateProject = {
  _count: ProjectCountAggregateOutputType | null
  _min: ProjectMinAggregateOutputType | null
  _max: ProjectMaxAggregateOutputType | null
}

export type ProjectMinAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  typeId: string | null
  status: $Enums.ProjectStatus | null
  groupId: string | null
  guideId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProjectMaxAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  typeId: string | null
  status: $Enums.ProjectStatus | null
  groupId: string | null
  guideId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProjectCountAggregateOutputType = {
  id: number
  title: number
  description: number
  typeId: number
  status: number
  groupId: number
  guideId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ProjectMinAggregateInputType = {
  id?: true
  title?: true
  description?: true
  typeId?: true
  status?: true
  groupId?: true
  guideId?: true
  createdAt?: true
  updatedAt?: true
}

export type ProjectMaxAggregateInputType = {
  id?: true
  title?: true
  description?: true
  typeId?: true
  status?: true
  groupId?: true
  guideId?: true
  createdAt?: true
  updatedAt?: true
}

export type ProjectCountAggregateInputType = {
  id?: true
  title?: true
  description?: true
  typeId?: true
  status?: true
  groupId?: true
  guideId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ProjectAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Project to aggregate.
   */
  where?: Prisma.ProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Projects to fetch.
   */
  orderBy?: Prisma.ProjectOrderByWithRelationInput | Prisma.ProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Projects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Projects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Projects
  **/
  _count?: true | ProjectCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProjectMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProjectMaxAggregateInputType
}

export type GetProjectAggregateType<T extends ProjectAggregateArgs> = {
      [P in keyof T & keyof AggregateProject]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProject[P]>
    : Prisma.GetScalarType<T[P], AggregateProject[P]>
}




export type ProjectGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProjectWhereInput
  orderBy?: Prisma.ProjectOrderByWithAggregationInput | Prisma.ProjectOrderByWithAggregationInput[]
  by: Prisma.ProjectScalarFieldEnum[] | Prisma.ProjectScalarFieldEnum
  having?: Prisma.ProjectScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProjectCountAggregateInputType | true
  _min?: ProjectMinAggregateInputType
  _max?: ProjectMaxAggregateInputType
}

export type ProjectGroupByOutputType = {
  id: string
  title: string
  description: string
  typeId: string
  status: $Enums.ProjectStatus
  groupId: string
  guideId: string | null
  createdAt: Date
  updatedAt: Date
  _count: ProjectCountAggregateOutputType | null
  _min: ProjectMinAggregateOutputType | null
  _max: ProjectMaxAggregateOutputType | null
}

type GetProjectGroupByPayload<T extends ProjectGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProjectGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProjectGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProjectGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProjectGroupByOutputType[P]>
      }
    >
  >



export type ProjectWhereInput = {
  AND?: Prisma.ProjectWhereInput | Prisma.ProjectWhereInput[]
  OR?: Prisma.ProjectWhereInput[]
  NOT?: Prisma.ProjectWhereInput | Prisma.ProjectWhereInput[]
  id?: Prisma.StringFilter<"Project"> | string
  title?: Prisma.StringFilter<"Project"> | string
  description?: Prisma.StringFilter<"Project"> | string
  typeId?: Prisma.StringFilter<"Project"> | string
  status?: Prisma.EnumProjectStatusFilter<"Project"> | $Enums.ProjectStatus
  groupId?: Prisma.StringFilter<"Project"> | string
  guideId?: Prisma.StringNullableFilter<"Project"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Project"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Project"> | Date | string
  Type?: Prisma.XOR<Prisma.ProjectTypeScalarRelationFilter, Prisma.ProjectTypeWhereInput>
  Document?: Prisma.DocumentListRelationFilter
  Meeting?: Prisma.MeetingListRelationFilter
  Milestone?: Prisma.MilestoneListRelationFilter
  ProjectGroup?: Prisma.XOR<Prisma.ProjectGroupScalarRelationFilter, Prisma.ProjectGroupWhereInput>
  FacultyProfile?: Prisma.XOR<Prisma.FacultyProfileNullableScalarRelationFilter, Prisma.FacultyProfileWhereInput> | null
}

export type ProjectOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  typeId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  guideId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  Type?: Prisma.ProjectTypeOrderByWithRelationInput
  Document?: Prisma.DocumentOrderByRelationAggregateInput
  Meeting?: Prisma.MeetingOrderByRelationAggregateInput
  Milestone?: Prisma.MilestoneOrderByRelationAggregateInput
  ProjectGroup?: Prisma.ProjectGroupOrderByWithRelationInput
  FacultyProfile?: Prisma.FacultyProfileOrderByWithRelationInput
}

export type ProjectWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  groupId?: string
  AND?: Prisma.ProjectWhereInput | Prisma.ProjectWhereInput[]
  OR?: Prisma.ProjectWhereInput[]
  NOT?: Prisma.ProjectWhereInput | Prisma.ProjectWhereInput[]
  title?: Prisma.StringFilter<"Project"> | string
  description?: Prisma.StringFilter<"Project"> | string
  typeId?: Prisma.StringFilter<"Project"> | string
  status?: Prisma.EnumProjectStatusFilter<"Project"> | $Enums.ProjectStatus
  guideId?: Prisma.StringNullableFilter<"Project"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Project"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Project"> | Date | string
  Type?: Prisma.XOR<Prisma.ProjectTypeScalarRelationFilter, Prisma.ProjectTypeWhereInput>
  Document?: Prisma.DocumentListRelationFilter
  Meeting?: Prisma.MeetingListRelationFilter
  Milestone?: Prisma.MilestoneListRelationFilter
  ProjectGroup?: Prisma.XOR<Prisma.ProjectGroupScalarRelationFilter, Prisma.ProjectGroupWhereInput>
  FacultyProfile?: Prisma.XOR<Prisma.FacultyProfileNullableScalarRelationFilter, Prisma.FacultyProfileWhereInput> | null
}, "id" | "groupId">

export type ProjectOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  typeId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  guideId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ProjectCountOrderByAggregateInput
  _max?: Prisma.ProjectMaxOrderByAggregateInput
  _min?: Prisma.ProjectMinOrderByAggregateInput
}

export type ProjectScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProjectScalarWhereWithAggregatesInput | Prisma.ProjectScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProjectScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProjectScalarWhereWithAggregatesInput | Prisma.ProjectScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Project"> | string
  title?: Prisma.StringWithAggregatesFilter<"Project"> | string
  description?: Prisma.StringWithAggregatesFilter<"Project"> | string
  typeId?: Prisma.StringWithAggregatesFilter<"Project"> | string
  status?: Prisma.EnumProjectStatusWithAggregatesFilter<"Project"> | $Enums.ProjectStatus
  groupId?: Prisma.StringWithAggregatesFilter<"Project"> | string
  guideId?: Prisma.StringNullableWithAggregatesFilter<"Project"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Project"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Project"> | Date | string
}

export type ProjectCreateInput = {
  id?: string
  title: string
  description: string
  status?: $Enums.ProjectStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  Type: Prisma.ProjectTypeCreateNestedOneWithoutProjectInput
  Document?: Prisma.DocumentCreateNestedManyWithoutProjectInput
  Meeting?: Prisma.MeetingCreateNestedManyWithoutProjectInput
  Milestone?: Prisma.MilestoneCreateNestedManyWithoutProjectInput
  ProjectGroup: Prisma.ProjectGroupCreateNestedOneWithoutProjectInput
  FacultyProfile?: Prisma.FacultyProfileCreateNestedOneWithoutProjectInput
}

export type ProjectUncheckedCreateInput = {
  id?: string
  title: string
  description: string
  typeId: string
  status?: $Enums.ProjectStatus
  groupId: string
  guideId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  Document?: Prisma.DocumentUncheckedCreateNestedManyWithoutProjectInput
  Meeting?: Prisma.MeetingUncheckedCreateNestedManyWithoutProjectInput
  Milestone?: Prisma.MilestoneUncheckedCreateNestedManyWithoutProjectInput
}

export type ProjectUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Type?: Prisma.ProjectTypeUpdateOneRequiredWithoutProjectNestedInput
  Document?: Prisma.DocumentUpdateManyWithoutProjectNestedInput
  Meeting?: Prisma.MeetingUpdateManyWithoutProjectNestedInput
  Milestone?: Prisma.MilestoneUpdateManyWithoutProjectNestedInput
  ProjectGroup?: Prisma.ProjectGroupUpdateOneRequiredWithoutProjectNestedInput
  FacultyProfile?: Prisma.FacultyProfileUpdateOneWithoutProjectNestedInput
}

export type ProjectUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  typeId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  groupId?: Prisma.StringFieldUpdateOperationsInput | string
  guideId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Document?: Prisma.DocumentUncheckedUpdateManyWithoutProjectNestedInput
  Meeting?: Prisma.MeetingUncheckedUpdateManyWithoutProjectNestedInput
  Milestone?: Prisma.MilestoneUncheckedUpdateManyWithoutProjectNestedInput
}

export type ProjectCreateManyInput = {
  id?: string
  title: string
  description: string
  typeId: string
  status?: $Enums.ProjectStatus
  groupId: string
  guideId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProjectUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProjectUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  typeId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  groupId?: Prisma.StringFieldUpdateOperationsInput | string
  guideId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProjectScalarRelationFilter = {
  is?: Prisma.ProjectWhereInput
  isNot?: Prisma.ProjectWhereInput
}

export type ProjectListRelationFilter = {
  every?: Prisma.ProjectWhereInput
  some?: Prisma.ProjectWhereInput
  none?: Prisma.ProjectWhereInput
}

export type ProjectOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProjectCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  typeId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  guideId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProjectMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  typeId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  guideId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProjectMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  typeId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  guideId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProjectNullableScalarRelationFilter = {
  is?: Prisma.ProjectWhereInput | null
  isNot?: Prisma.ProjectWhereInput | null
}

export type ProjectCreateNestedOneWithoutDocumentInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutDocumentInput, Prisma.ProjectUncheckedCreateWithoutDocumentInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutDocumentInput
  connect?: Prisma.ProjectWhereUniqueInput
}

export type ProjectUpdateOneRequiredWithoutDocumentNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutDocumentInput, Prisma.ProjectUncheckedCreateWithoutDocumentInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutDocumentInput
  upsert?: Prisma.ProjectUpsertWithoutDocumentInput
  connect?: Prisma.ProjectWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProjectUpdateToOneWithWhereWithoutDocumentInput, Prisma.ProjectUpdateWithoutDocumentInput>, Prisma.ProjectUncheckedUpdateWithoutDocumentInput>
}

export type ProjectCreateNestedManyWithoutFacultyProfileInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutFacultyProfileInput, Prisma.ProjectUncheckedCreateWithoutFacultyProfileInput> | Prisma.ProjectCreateWithoutFacultyProfileInput[] | Prisma.ProjectUncheckedCreateWithoutFacultyProfileInput[]
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutFacultyProfileInput | Prisma.ProjectCreateOrConnectWithoutFacultyProfileInput[]
  createMany?: Prisma.ProjectCreateManyFacultyProfileInputEnvelope
  connect?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
}

export type ProjectUncheckedCreateNestedManyWithoutFacultyProfileInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutFacultyProfileInput, Prisma.ProjectUncheckedCreateWithoutFacultyProfileInput> | Prisma.ProjectCreateWithoutFacultyProfileInput[] | Prisma.ProjectUncheckedCreateWithoutFacultyProfileInput[]
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutFacultyProfileInput | Prisma.ProjectCreateOrConnectWithoutFacultyProfileInput[]
  createMany?: Prisma.ProjectCreateManyFacultyProfileInputEnvelope
  connect?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
}

export type ProjectUpdateManyWithoutFacultyProfileNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutFacultyProfileInput, Prisma.ProjectUncheckedCreateWithoutFacultyProfileInput> | Prisma.ProjectCreateWithoutFacultyProfileInput[] | Prisma.ProjectUncheckedCreateWithoutFacultyProfileInput[]
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutFacultyProfileInput | Prisma.ProjectCreateOrConnectWithoutFacultyProfileInput[]
  upsert?: Prisma.ProjectUpsertWithWhereUniqueWithoutFacultyProfileInput | Prisma.ProjectUpsertWithWhereUniqueWithoutFacultyProfileInput[]
  createMany?: Prisma.ProjectCreateManyFacultyProfileInputEnvelope
  set?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  disconnect?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  delete?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  connect?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  update?: Prisma.ProjectUpdateWithWhereUniqueWithoutFacultyProfileInput | Prisma.ProjectUpdateWithWhereUniqueWithoutFacultyProfileInput[]
  updateMany?: Prisma.ProjectUpdateManyWithWhereWithoutFacultyProfileInput | Prisma.ProjectUpdateManyWithWhereWithoutFacultyProfileInput[]
  deleteMany?: Prisma.ProjectScalarWhereInput | Prisma.ProjectScalarWhereInput[]
}

export type ProjectUncheckedUpdateManyWithoutFacultyProfileNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutFacultyProfileInput, Prisma.ProjectUncheckedCreateWithoutFacultyProfileInput> | Prisma.ProjectCreateWithoutFacultyProfileInput[] | Prisma.ProjectUncheckedCreateWithoutFacultyProfileInput[]
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutFacultyProfileInput | Prisma.ProjectCreateOrConnectWithoutFacultyProfileInput[]
  upsert?: Prisma.ProjectUpsertWithWhereUniqueWithoutFacultyProfileInput | Prisma.ProjectUpsertWithWhereUniqueWithoutFacultyProfileInput[]
  createMany?: Prisma.ProjectCreateManyFacultyProfileInputEnvelope
  set?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  disconnect?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  delete?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  connect?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  update?: Prisma.ProjectUpdateWithWhereUniqueWithoutFacultyProfileInput | Prisma.ProjectUpdateWithWhereUniqueWithoutFacultyProfileInput[]
  updateMany?: Prisma.ProjectUpdateManyWithWhereWithoutFacultyProfileInput | Prisma.ProjectUpdateManyWithWhereWithoutFacultyProfileInput[]
  deleteMany?: Prisma.ProjectScalarWhereInput | Prisma.ProjectScalarWhereInput[]
}

export type ProjectCreateNestedOneWithoutMeetingInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutMeetingInput, Prisma.ProjectUncheckedCreateWithoutMeetingInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutMeetingInput
  connect?: Prisma.ProjectWhereUniqueInput
}

export type ProjectUpdateOneRequiredWithoutMeetingNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutMeetingInput, Prisma.ProjectUncheckedCreateWithoutMeetingInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutMeetingInput
  upsert?: Prisma.ProjectUpsertWithoutMeetingInput
  connect?: Prisma.ProjectWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProjectUpdateToOneWithWhereWithoutMeetingInput, Prisma.ProjectUpdateWithoutMeetingInput>, Prisma.ProjectUncheckedUpdateWithoutMeetingInput>
}

export type ProjectCreateNestedOneWithoutMilestoneInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutMilestoneInput, Prisma.ProjectUncheckedCreateWithoutMilestoneInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutMilestoneInput
  connect?: Prisma.ProjectWhereUniqueInput
}

export type ProjectUpdateOneRequiredWithoutMilestoneNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutMilestoneInput, Prisma.ProjectUncheckedCreateWithoutMilestoneInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutMilestoneInput
  upsert?: Prisma.ProjectUpsertWithoutMilestoneInput
  connect?: Prisma.ProjectWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProjectUpdateToOneWithWhereWithoutMilestoneInput, Prisma.ProjectUpdateWithoutMilestoneInput>, Prisma.ProjectUncheckedUpdateWithoutMilestoneInput>
}

export type EnumProjectStatusFieldUpdateOperationsInput = {
  set?: $Enums.ProjectStatus
}

export type ProjectCreateNestedManyWithoutTypeInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutTypeInput, Prisma.ProjectUncheckedCreateWithoutTypeInput> | Prisma.ProjectCreateWithoutTypeInput[] | Prisma.ProjectUncheckedCreateWithoutTypeInput[]
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutTypeInput | Prisma.ProjectCreateOrConnectWithoutTypeInput[]
  createMany?: Prisma.ProjectCreateManyTypeInputEnvelope
  connect?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
}

export type ProjectUncheckedCreateNestedManyWithoutTypeInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutTypeInput, Prisma.ProjectUncheckedCreateWithoutTypeInput> | Prisma.ProjectCreateWithoutTypeInput[] | Prisma.ProjectUncheckedCreateWithoutTypeInput[]
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutTypeInput | Prisma.ProjectCreateOrConnectWithoutTypeInput[]
  createMany?: Prisma.ProjectCreateManyTypeInputEnvelope
  connect?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
}

export type ProjectUpdateManyWithoutTypeNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutTypeInput, Prisma.ProjectUncheckedCreateWithoutTypeInput> | Prisma.ProjectCreateWithoutTypeInput[] | Prisma.ProjectUncheckedCreateWithoutTypeInput[]
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutTypeInput | Prisma.ProjectCreateOrConnectWithoutTypeInput[]
  upsert?: Prisma.ProjectUpsertWithWhereUniqueWithoutTypeInput | Prisma.ProjectUpsertWithWhereUniqueWithoutTypeInput[]
  createMany?: Prisma.ProjectCreateManyTypeInputEnvelope
  set?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  disconnect?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  delete?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  connect?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  update?: Prisma.ProjectUpdateWithWhereUniqueWithoutTypeInput | Prisma.ProjectUpdateWithWhereUniqueWithoutTypeInput[]
  updateMany?: Prisma.ProjectUpdateManyWithWhereWithoutTypeInput | Prisma.ProjectUpdateManyWithWhereWithoutTypeInput[]
  deleteMany?: Prisma.ProjectScalarWhereInput | Prisma.ProjectScalarWhereInput[]
}

export type ProjectUncheckedUpdateManyWithoutTypeNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutTypeInput, Prisma.ProjectUncheckedCreateWithoutTypeInput> | Prisma.ProjectCreateWithoutTypeInput[] | Prisma.ProjectUncheckedCreateWithoutTypeInput[]
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutTypeInput | Prisma.ProjectCreateOrConnectWithoutTypeInput[]
  upsert?: Prisma.ProjectUpsertWithWhereUniqueWithoutTypeInput | Prisma.ProjectUpsertWithWhereUniqueWithoutTypeInput[]
  createMany?: Prisma.ProjectCreateManyTypeInputEnvelope
  set?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  disconnect?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  delete?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  connect?: Prisma.ProjectWhereUniqueInput | Prisma.ProjectWhereUniqueInput[]
  update?: Prisma.ProjectUpdateWithWhereUniqueWithoutTypeInput | Prisma.ProjectUpdateWithWhereUniqueWithoutTypeInput[]
  updateMany?: Prisma.ProjectUpdateManyWithWhereWithoutTypeInput | Prisma.ProjectUpdateManyWithWhereWithoutTypeInput[]
  deleteMany?: Prisma.ProjectScalarWhereInput | Prisma.ProjectScalarWhereInput[]
}

export type ProjectCreateNestedOneWithoutProjectGroupInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutProjectGroupInput, Prisma.ProjectUncheckedCreateWithoutProjectGroupInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutProjectGroupInput
  connect?: Prisma.ProjectWhereUniqueInput
}

export type ProjectUncheckedCreateNestedOneWithoutProjectGroupInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutProjectGroupInput, Prisma.ProjectUncheckedCreateWithoutProjectGroupInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutProjectGroupInput
  connect?: Prisma.ProjectWhereUniqueInput
}

export type ProjectUpdateOneWithoutProjectGroupNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutProjectGroupInput, Prisma.ProjectUncheckedCreateWithoutProjectGroupInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutProjectGroupInput
  upsert?: Prisma.ProjectUpsertWithoutProjectGroupInput
  disconnect?: Prisma.ProjectWhereInput | boolean
  delete?: Prisma.ProjectWhereInput | boolean
  connect?: Prisma.ProjectWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProjectUpdateToOneWithWhereWithoutProjectGroupInput, Prisma.ProjectUpdateWithoutProjectGroupInput>, Prisma.ProjectUncheckedUpdateWithoutProjectGroupInput>
}

export type ProjectUncheckedUpdateOneWithoutProjectGroupNestedInput = {
  create?: Prisma.XOR<Prisma.ProjectCreateWithoutProjectGroupInput, Prisma.ProjectUncheckedCreateWithoutProjectGroupInput>
  connectOrCreate?: Prisma.ProjectCreateOrConnectWithoutProjectGroupInput
  upsert?: Prisma.ProjectUpsertWithoutProjectGroupInput
  disconnect?: Prisma.ProjectWhereInput | boolean
  delete?: Prisma.ProjectWhereInput | boolean
  connect?: Prisma.ProjectWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProjectUpdateToOneWithWhereWithoutProjectGroupInput, Prisma.ProjectUpdateWithoutProjectGroupInput>, Prisma.ProjectUncheckedUpdateWithoutProjectGroupInput>
}

export type ProjectCreateWithoutDocumentInput = {
  id?: string
  title: string
  description: string
  status?: $Enums.ProjectStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  Type: Prisma.ProjectTypeCreateNestedOneWithoutProjectInput
  Meeting?: Prisma.MeetingCreateNestedManyWithoutProjectInput
  Milestone?: Prisma.MilestoneCreateNestedManyWithoutProjectInput
  ProjectGroup: Prisma.ProjectGroupCreateNestedOneWithoutProjectInput
  FacultyProfile?: Prisma.FacultyProfileCreateNestedOneWithoutProjectInput
}

export type ProjectUncheckedCreateWithoutDocumentInput = {
  id?: string
  title: string
  description: string
  typeId: string
  status?: $Enums.ProjectStatus
  groupId: string
  guideId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  Meeting?: Prisma.MeetingUncheckedCreateNestedManyWithoutProjectInput
  Milestone?: Prisma.MilestoneUncheckedCreateNestedManyWithoutProjectInput
}

export type ProjectCreateOrConnectWithoutDocumentInput = {
  where: Prisma.ProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.ProjectCreateWithoutDocumentInput, Prisma.ProjectUncheckedCreateWithoutDocumentInput>
}

export type ProjectUpsertWithoutDocumentInput = {
  update: Prisma.XOR<Prisma.ProjectUpdateWithoutDocumentInput, Prisma.ProjectUncheckedUpdateWithoutDocumentInput>
  create: Prisma.XOR<Prisma.ProjectCreateWithoutDocumentInput, Prisma.ProjectUncheckedCreateWithoutDocumentInput>
  where?: Prisma.ProjectWhereInput
}

export type ProjectUpdateToOneWithWhereWithoutDocumentInput = {
  where?: Prisma.ProjectWhereInput
  data: Prisma.XOR<Prisma.ProjectUpdateWithoutDocumentInput, Prisma.ProjectUncheckedUpdateWithoutDocumentInput>
}

export type ProjectUpdateWithoutDocumentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Type?: Prisma.ProjectTypeUpdateOneRequiredWithoutProjectNestedInput
  Meeting?: Prisma.MeetingUpdateManyWithoutProjectNestedInput
  Milestone?: Prisma.MilestoneUpdateManyWithoutProjectNestedInput
  ProjectGroup?: Prisma.ProjectGroupUpdateOneRequiredWithoutProjectNestedInput
  FacultyProfile?: Prisma.FacultyProfileUpdateOneWithoutProjectNestedInput
}

export type ProjectUncheckedUpdateWithoutDocumentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  typeId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  groupId?: Prisma.StringFieldUpdateOperationsInput | string
  guideId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Meeting?: Prisma.MeetingUncheckedUpdateManyWithoutProjectNestedInput
  Milestone?: Prisma.MilestoneUncheckedUpdateManyWithoutProjectNestedInput
}

export type ProjectCreateWithoutFacultyProfileInput = {
  id?: string
  title: string
  description: string
  status?: $Enums.ProjectStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  Type: Prisma.ProjectTypeCreateNestedOneWithoutProjectInput
  Document?: Prisma.DocumentCreateNestedManyWithoutProjectInput
  Meeting?: Prisma.MeetingCreateNestedManyWithoutProjectInput
  Milestone?: Prisma.MilestoneCreateNestedManyWithoutProjectInput
  ProjectGroup: Prisma.ProjectGroupCreateNestedOneWithoutProjectInput
}

export type ProjectUncheckedCreateWithoutFacultyProfileInput = {
  id?: string
  title: string
  description: string
  typeId: string
  status?: $Enums.ProjectStatus
  groupId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  Document?: Prisma.DocumentUncheckedCreateNestedManyWithoutProjectInput
  Meeting?: Prisma.MeetingUncheckedCreateNestedManyWithoutProjectInput
  Milestone?: Prisma.MilestoneUncheckedCreateNestedManyWithoutProjectInput
}

export type ProjectCreateOrConnectWithoutFacultyProfileInput = {
  where: Prisma.ProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.ProjectCreateWithoutFacultyProfileInput, Prisma.ProjectUncheckedCreateWithoutFacultyProfileInput>
}

export type ProjectCreateManyFacultyProfileInputEnvelope = {
  data: Prisma.ProjectCreateManyFacultyProfileInput | Prisma.ProjectCreateManyFacultyProfileInput[]
  skipDuplicates?: boolean
}

export type ProjectUpsertWithWhereUniqueWithoutFacultyProfileInput = {
  where: Prisma.ProjectWhereUniqueInput
  update: Prisma.XOR<Prisma.ProjectUpdateWithoutFacultyProfileInput, Prisma.ProjectUncheckedUpdateWithoutFacultyProfileInput>
  create: Prisma.XOR<Prisma.ProjectCreateWithoutFacultyProfileInput, Prisma.ProjectUncheckedCreateWithoutFacultyProfileInput>
}

export type ProjectUpdateWithWhereUniqueWithoutFacultyProfileInput = {
  where: Prisma.ProjectWhereUniqueInput
  data: Prisma.XOR<Prisma.ProjectUpdateWithoutFacultyProfileInput, Prisma.ProjectUncheckedUpdateWithoutFacultyProfileInput>
}

export type ProjectUpdateManyWithWhereWithoutFacultyProfileInput = {
  where: Prisma.ProjectScalarWhereInput
  data: Prisma.XOR<Prisma.ProjectUpdateManyMutationInput, Prisma.ProjectUncheckedUpdateManyWithoutFacultyProfileInput>
}

export type ProjectScalarWhereInput = {
  AND?: Prisma.ProjectScalarWhereInput | Prisma.ProjectScalarWhereInput[]
  OR?: Prisma.ProjectScalarWhereInput[]
  NOT?: Prisma.ProjectScalarWhereInput | Prisma.ProjectScalarWhereInput[]
  id?: Prisma.StringFilter<"Project"> | string
  title?: Prisma.StringFilter<"Project"> | string
  description?: Prisma.StringFilter<"Project"> | string
  typeId?: Prisma.StringFilter<"Project"> | string
  status?: Prisma.EnumProjectStatusFilter<"Project"> | $Enums.ProjectStatus
  groupId?: Prisma.StringFilter<"Project"> | string
  guideId?: Prisma.StringNullableFilter<"Project"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Project"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Project"> | Date | string
}

export type ProjectCreateWithoutMeetingInput = {
  id?: string
  title: string
  description: string
  status?: $Enums.ProjectStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  Type: Prisma.ProjectTypeCreateNestedOneWithoutProjectInput
  Document?: Prisma.DocumentCreateNestedManyWithoutProjectInput
  Milestone?: Prisma.MilestoneCreateNestedManyWithoutProjectInput
  ProjectGroup: Prisma.ProjectGroupCreateNestedOneWithoutProjectInput
  FacultyProfile?: Prisma.FacultyProfileCreateNestedOneWithoutProjectInput
}

export type ProjectUncheckedCreateWithoutMeetingInput = {
  id?: string
  title: string
  description: string
  typeId: string
  status?: $Enums.ProjectStatus
  groupId: string
  guideId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  Document?: Prisma.DocumentUncheckedCreateNestedManyWithoutProjectInput
  Milestone?: Prisma.MilestoneUncheckedCreateNestedManyWithoutProjectInput
}

export type ProjectCreateOrConnectWithoutMeetingInput = {
  where: Prisma.ProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.ProjectCreateWithoutMeetingInput, Prisma.ProjectUncheckedCreateWithoutMeetingInput>
}

export type ProjectUpsertWithoutMeetingInput = {
  update: Prisma.XOR<Prisma.ProjectUpdateWithoutMeetingInput, Prisma.ProjectUncheckedUpdateWithoutMeetingInput>
  create: Prisma.XOR<Prisma.ProjectCreateWithoutMeetingInput, Prisma.ProjectUncheckedCreateWithoutMeetingInput>
  where?: Prisma.ProjectWhereInput
}

export type ProjectUpdateToOneWithWhereWithoutMeetingInput = {
  where?: Prisma.ProjectWhereInput
  data: Prisma.XOR<Prisma.ProjectUpdateWithoutMeetingInput, Prisma.ProjectUncheckedUpdateWithoutMeetingInput>
}

export type ProjectUpdateWithoutMeetingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Type?: Prisma.ProjectTypeUpdateOneRequiredWithoutProjectNestedInput
  Document?: Prisma.DocumentUpdateManyWithoutProjectNestedInput
  Milestone?: Prisma.MilestoneUpdateManyWithoutProjectNestedInput
  ProjectGroup?: Prisma.ProjectGroupUpdateOneRequiredWithoutProjectNestedInput
  FacultyProfile?: Prisma.FacultyProfileUpdateOneWithoutProjectNestedInput
}

export type ProjectUncheckedUpdateWithoutMeetingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  typeId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  groupId?: Prisma.StringFieldUpdateOperationsInput | string
  guideId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Document?: Prisma.DocumentUncheckedUpdateManyWithoutProjectNestedInput
  Milestone?: Prisma.MilestoneUncheckedUpdateManyWithoutProjectNestedInput
}

export type ProjectCreateWithoutMilestoneInput = {
  id?: string
  title: string
  description: string
  status?: $Enums.ProjectStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  Type: Prisma.ProjectTypeCreateNestedOneWithoutProjectInput
  Document?: Prisma.DocumentCreateNestedManyWithoutProjectInput
  Meeting?: Prisma.MeetingCreateNestedManyWithoutProjectInput
  ProjectGroup: Prisma.ProjectGroupCreateNestedOneWithoutProjectInput
  FacultyProfile?: Prisma.FacultyProfileCreateNestedOneWithoutProjectInput
}

export type ProjectUncheckedCreateWithoutMilestoneInput = {
  id?: string
  title: string
  description: string
  typeId: string
  status?: $Enums.ProjectStatus
  groupId: string
  guideId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  Document?: Prisma.DocumentUncheckedCreateNestedManyWithoutProjectInput
  Meeting?: Prisma.MeetingUncheckedCreateNestedManyWithoutProjectInput
}

export type ProjectCreateOrConnectWithoutMilestoneInput = {
  where: Prisma.ProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.ProjectCreateWithoutMilestoneInput, Prisma.ProjectUncheckedCreateWithoutMilestoneInput>
}

export type ProjectUpsertWithoutMilestoneInput = {
  update: Prisma.XOR<Prisma.ProjectUpdateWithoutMilestoneInput, Prisma.ProjectUncheckedUpdateWithoutMilestoneInput>
  create: Prisma.XOR<Prisma.ProjectCreateWithoutMilestoneInput, Prisma.ProjectUncheckedCreateWithoutMilestoneInput>
  where?: Prisma.ProjectWhereInput
}

export type ProjectUpdateToOneWithWhereWithoutMilestoneInput = {
  where?: Prisma.ProjectWhereInput
  data: Prisma.XOR<Prisma.ProjectUpdateWithoutMilestoneInput, Prisma.ProjectUncheckedUpdateWithoutMilestoneInput>
}

export type ProjectUpdateWithoutMilestoneInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Type?: Prisma.ProjectTypeUpdateOneRequiredWithoutProjectNestedInput
  Document?: Prisma.DocumentUpdateManyWithoutProjectNestedInput
  Meeting?: Prisma.MeetingUpdateManyWithoutProjectNestedInput
  ProjectGroup?: Prisma.ProjectGroupUpdateOneRequiredWithoutProjectNestedInput
  FacultyProfile?: Prisma.FacultyProfileUpdateOneWithoutProjectNestedInput
}

export type ProjectUncheckedUpdateWithoutMilestoneInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  typeId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  groupId?: Prisma.StringFieldUpdateOperationsInput | string
  guideId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Document?: Prisma.DocumentUncheckedUpdateManyWithoutProjectNestedInput
  Meeting?: Prisma.MeetingUncheckedUpdateManyWithoutProjectNestedInput
}

export type ProjectCreateWithoutTypeInput = {
  id?: string
  title: string
  description: string
  status?: $Enums.ProjectStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  Document?: Prisma.DocumentCreateNestedManyWithoutProjectInput
  Meeting?: Prisma.MeetingCreateNestedManyWithoutProjectInput
  Milestone?: Prisma.MilestoneCreateNestedManyWithoutProjectInput
  ProjectGroup: Prisma.ProjectGroupCreateNestedOneWithoutProjectInput
  FacultyProfile?: Prisma.FacultyProfileCreateNestedOneWithoutProjectInput
}

export type ProjectUncheckedCreateWithoutTypeInput = {
  id?: string
  title: string
  description: string
  status?: $Enums.ProjectStatus
  groupId: string
  guideId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  Document?: Prisma.DocumentUncheckedCreateNestedManyWithoutProjectInput
  Meeting?: Prisma.MeetingUncheckedCreateNestedManyWithoutProjectInput
  Milestone?: Prisma.MilestoneUncheckedCreateNestedManyWithoutProjectInput
}

export type ProjectCreateOrConnectWithoutTypeInput = {
  where: Prisma.ProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.ProjectCreateWithoutTypeInput, Prisma.ProjectUncheckedCreateWithoutTypeInput>
}

export type ProjectCreateManyTypeInputEnvelope = {
  data: Prisma.ProjectCreateManyTypeInput | Prisma.ProjectCreateManyTypeInput[]
  skipDuplicates?: boolean
}

export type ProjectUpsertWithWhereUniqueWithoutTypeInput = {
  where: Prisma.ProjectWhereUniqueInput
  update: Prisma.XOR<Prisma.ProjectUpdateWithoutTypeInput, Prisma.ProjectUncheckedUpdateWithoutTypeInput>
  create: Prisma.XOR<Prisma.ProjectCreateWithoutTypeInput, Prisma.ProjectUncheckedCreateWithoutTypeInput>
}

export type ProjectUpdateWithWhereUniqueWithoutTypeInput = {
  where: Prisma.ProjectWhereUniqueInput
  data: Prisma.XOR<Prisma.ProjectUpdateWithoutTypeInput, Prisma.ProjectUncheckedUpdateWithoutTypeInput>
}

export type ProjectUpdateManyWithWhereWithoutTypeInput = {
  where: Prisma.ProjectScalarWhereInput
  data: Prisma.XOR<Prisma.ProjectUpdateManyMutationInput, Prisma.ProjectUncheckedUpdateManyWithoutTypeInput>
}

export type ProjectCreateWithoutProjectGroupInput = {
  id?: string
  title: string
  description: string
  status?: $Enums.ProjectStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  Type: Prisma.ProjectTypeCreateNestedOneWithoutProjectInput
  Document?: Prisma.DocumentCreateNestedManyWithoutProjectInput
  Meeting?: Prisma.MeetingCreateNestedManyWithoutProjectInput
  Milestone?: Prisma.MilestoneCreateNestedManyWithoutProjectInput
  FacultyProfile?: Prisma.FacultyProfileCreateNestedOneWithoutProjectInput
}

export type ProjectUncheckedCreateWithoutProjectGroupInput = {
  id?: string
  title: string
  description: string
  typeId: string
  status?: $Enums.ProjectStatus
  guideId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  Document?: Prisma.DocumentUncheckedCreateNestedManyWithoutProjectInput
  Meeting?: Prisma.MeetingUncheckedCreateNestedManyWithoutProjectInput
  Milestone?: Prisma.MilestoneUncheckedCreateNestedManyWithoutProjectInput
}

export type ProjectCreateOrConnectWithoutProjectGroupInput = {
  where: Prisma.ProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.ProjectCreateWithoutProjectGroupInput, Prisma.ProjectUncheckedCreateWithoutProjectGroupInput>
}

export type ProjectUpsertWithoutProjectGroupInput = {
  update: Prisma.XOR<Prisma.ProjectUpdateWithoutProjectGroupInput, Prisma.ProjectUncheckedUpdateWithoutProjectGroupInput>
  create: Prisma.XOR<Prisma.ProjectCreateWithoutProjectGroupInput, Prisma.ProjectUncheckedCreateWithoutProjectGroupInput>
  where?: Prisma.ProjectWhereInput
}

export type ProjectUpdateToOneWithWhereWithoutProjectGroupInput = {
  where?: Prisma.ProjectWhereInput
  data: Prisma.XOR<Prisma.ProjectUpdateWithoutProjectGroupInput, Prisma.ProjectUncheckedUpdateWithoutProjectGroupInput>
}

export type ProjectUpdateWithoutProjectGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Type?: Prisma.ProjectTypeUpdateOneRequiredWithoutProjectNestedInput
  Document?: Prisma.DocumentUpdateManyWithoutProjectNestedInput
  Meeting?: Prisma.MeetingUpdateManyWithoutProjectNestedInput
  Milestone?: Prisma.MilestoneUpdateManyWithoutProjectNestedInput
  FacultyProfile?: Prisma.FacultyProfileUpdateOneWithoutProjectNestedInput
}

export type ProjectUncheckedUpdateWithoutProjectGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  typeId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  guideId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Document?: Prisma.DocumentUncheckedUpdateManyWithoutProjectNestedInput
  Meeting?: Prisma.MeetingUncheckedUpdateManyWithoutProjectNestedInput
  Milestone?: Prisma.MilestoneUncheckedUpdateManyWithoutProjectNestedInput
}

export type ProjectCreateManyFacultyProfileInput = {
  id?: string
  title: string
  description: string
  typeId: string
  status?: $Enums.ProjectStatus
  groupId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProjectUpdateWithoutFacultyProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Type?: Prisma.ProjectTypeUpdateOneRequiredWithoutProjectNestedInput
  Document?: Prisma.DocumentUpdateManyWithoutProjectNestedInput
  Meeting?: Prisma.MeetingUpdateManyWithoutProjectNestedInput
  Milestone?: Prisma.MilestoneUpdateManyWithoutProjectNestedInput
  ProjectGroup?: Prisma.ProjectGroupUpdateOneRequiredWithoutProjectNestedInput
}

export type ProjectUncheckedUpdateWithoutFacultyProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  typeId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  groupId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Document?: Prisma.DocumentUncheckedUpdateManyWithoutProjectNestedInput
  Meeting?: Prisma.MeetingUncheckedUpdateManyWithoutProjectNestedInput
  Milestone?: Prisma.MilestoneUncheckedUpdateManyWithoutProjectNestedInput
}

export type ProjectUncheckedUpdateManyWithoutFacultyProfileInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  typeId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  groupId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProjectCreateManyTypeInput = {
  id?: string
  title: string
  description: string
  status?: $Enums.ProjectStatus
  groupId: string
  guideId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProjectUpdateWithoutTypeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Document?: Prisma.DocumentUpdateManyWithoutProjectNestedInput
  Meeting?: Prisma.MeetingUpdateManyWithoutProjectNestedInput
  Milestone?: Prisma.MilestoneUpdateManyWithoutProjectNestedInput
  ProjectGroup?: Prisma.ProjectGroupUpdateOneRequiredWithoutProjectNestedInput
  FacultyProfile?: Prisma.FacultyProfileUpdateOneWithoutProjectNestedInput
}

export type ProjectUncheckedUpdateWithoutTypeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  groupId?: Prisma.StringFieldUpdateOperationsInput | string
  guideId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  Document?: Prisma.DocumentUncheckedUpdateManyWithoutProjectNestedInput
  Meeting?: Prisma.MeetingUncheckedUpdateManyWithoutProjectNestedInput
  Milestone?: Prisma.MilestoneUncheckedUpdateManyWithoutProjectNestedInput
}

export type ProjectUncheckedUpdateManyWithoutTypeInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProjectStatusFieldUpdateOperationsInput | $Enums.ProjectStatus
  groupId?: Prisma.StringFieldUpdateOperationsInput | string
  guideId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type ProjectCountOutputType
 */

export type ProjectCountOutputType = {
  Document: number
  Meeting: number
  Milestone: number
}

export type ProjectCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Document?: boolean | ProjectCountOutputTypeCountDocumentArgs
  Meeting?: boolean | ProjectCountOutputTypeCountMeetingArgs
  Milestone?: boolean | ProjectCountOutputTypeCountMilestoneArgs
}

/**
 * ProjectCountOutputType without action
 */
export type ProjectCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectCountOutputType
   */
  select?: Prisma.ProjectCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ProjectCountOutputType without action
 */
export type ProjectCountOutputTypeCountDocumentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DocumentWhereInput
}

/**
 * ProjectCountOutputType without action
 */
export type ProjectCountOutputTypeCountMeetingArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MeetingWhereInput
}

/**
 * ProjectCountOutputType without action
 */
export type ProjectCountOutputTypeCountMilestoneArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MilestoneWhereInput
}


export type ProjectSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  typeId?: boolean
  status?: boolean
  groupId?: boolean
  guideId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  Type?: boolean | Prisma.ProjectTypeDefaultArgs<ExtArgs>
  Document?: boolean | Prisma.Project$DocumentArgs<ExtArgs>
  Meeting?: boolean | Prisma.Project$MeetingArgs<ExtArgs>
  Milestone?: boolean | Prisma.Project$MilestoneArgs<ExtArgs>
  ProjectGroup?: boolean | Prisma.ProjectGroupDefaultArgs<ExtArgs>
  FacultyProfile?: boolean | Prisma.Project$FacultyProfileArgs<ExtArgs>
  _count?: boolean | Prisma.ProjectCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["project"]>

export type ProjectSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  typeId?: boolean
  status?: boolean
  groupId?: boolean
  guideId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  Type?: boolean | Prisma.ProjectTypeDefaultArgs<ExtArgs>
  ProjectGroup?: boolean | Prisma.ProjectGroupDefaultArgs<ExtArgs>
  FacultyProfile?: boolean | Prisma.Project$FacultyProfileArgs<ExtArgs>
}, ExtArgs["result"]["project"]>

export type ProjectSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  typeId?: boolean
  status?: boolean
  groupId?: boolean
  guideId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  Type?: boolean | Prisma.ProjectTypeDefaultArgs<ExtArgs>
  ProjectGroup?: boolean | Prisma.ProjectGroupDefaultArgs<ExtArgs>
  FacultyProfile?: boolean | Prisma.Project$FacultyProfileArgs<ExtArgs>
}, ExtArgs["result"]["project"]>

export type ProjectSelectScalar = {
  id?: boolean
  title?: boolean
  description?: boolean
  typeId?: boolean
  status?: boolean
  groupId?: boolean
  guideId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ProjectOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "description" | "typeId" | "status" | "groupId" | "guideId" | "createdAt" | "updatedAt", ExtArgs["result"]["project"]>
export type ProjectInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Type?: boolean | Prisma.ProjectTypeDefaultArgs<ExtArgs>
  Document?: boolean | Prisma.Project$DocumentArgs<ExtArgs>
  Meeting?: boolean | Prisma.Project$MeetingArgs<ExtArgs>
  Milestone?: boolean | Prisma.Project$MilestoneArgs<ExtArgs>
  ProjectGroup?: boolean | Prisma.ProjectGroupDefaultArgs<ExtArgs>
  FacultyProfile?: boolean | Prisma.Project$FacultyProfileArgs<ExtArgs>
  _count?: boolean | Prisma.ProjectCountOutputTypeDefaultArgs<ExtArgs>
}
export type ProjectIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Type?: boolean | Prisma.ProjectTypeDefaultArgs<ExtArgs>
  ProjectGroup?: boolean | Prisma.ProjectGroupDefaultArgs<ExtArgs>
  FacultyProfile?: boolean | Prisma.Project$FacultyProfileArgs<ExtArgs>
}
export type ProjectIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Type?: boolean | Prisma.ProjectTypeDefaultArgs<ExtArgs>
  ProjectGroup?: boolean | Prisma.ProjectGroupDefaultArgs<ExtArgs>
  FacultyProfile?: boolean | Prisma.Project$FacultyProfileArgs<ExtArgs>
}

export type $ProjectPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Project"
  objects: {
    Type: Prisma.$ProjectTypePayload<ExtArgs>
    Document: Prisma.$DocumentPayload<ExtArgs>[]
    Meeting: Prisma.$MeetingPayload<ExtArgs>[]
    Milestone: Prisma.$MilestonePayload<ExtArgs>[]
    ProjectGroup: Prisma.$ProjectGroupPayload<ExtArgs>
    FacultyProfile: Prisma.$FacultyProfilePayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    description: string
    typeId: string
    status: $Enums.ProjectStatus
    groupId: string
    guideId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["project"]>
  composites: {}
}

export type ProjectGetPayload<S extends boolean | null | undefined | ProjectDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProjectPayload, S>

export type ProjectCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProjectFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProjectCountAggregateInputType | true
  }

export interface ProjectDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Project'], meta: { name: 'Project' } }
  /**
   * Find zero or one Project that matches the filter.
   * @param {ProjectFindUniqueArgs} args - Arguments to find a Project
   * @example
   * // Get one Project
   * const project = await prisma.project.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProjectFindUniqueArgs>(args: Prisma.SelectSubset<T, ProjectFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Project that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProjectFindUniqueOrThrowArgs} args - Arguments to find a Project
   * @example
   * // Get one Project
   * const project = await prisma.project.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProjectFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProjectFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Project that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectFindFirstArgs} args - Arguments to find a Project
   * @example
   * // Get one Project
   * const project = await prisma.project.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProjectFindFirstArgs>(args?: Prisma.SelectSubset<T, ProjectFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Project that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectFindFirstOrThrowArgs} args - Arguments to find a Project
   * @example
   * // Get one Project
   * const project = await prisma.project.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProjectFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProjectFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Projects that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Projects
   * const projects = await prisma.project.findMany()
   * 
   * // Get first 10 Projects
   * const projects = await prisma.project.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const projectWithIdOnly = await prisma.project.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProjectFindManyArgs>(args?: Prisma.SelectSubset<T, ProjectFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Project.
   * @param {ProjectCreateArgs} args - Arguments to create a Project.
   * @example
   * // Create one Project
   * const Project = await prisma.project.create({
   *   data: {
   *     // ... data to create a Project
   *   }
   * })
   * 
   */
  create<T extends ProjectCreateArgs>(args: Prisma.SelectSubset<T, ProjectCreateArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Projects.
   * @param {ProjectCreateManyArgs} args - Arguments to create many Projects.
   * @example
   * // Create many Projects
   * const project = await prisma.project.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProjectCreateManyArgs>(args?: Prisma.SelectSubset<T, ProjectCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Projects and returns the data saved in the database.
   * @param {ProjectCreateManyAndReturnArgs} args - Arguments to create many Projects.
   * @example
   * // Create many Projects
   * const project = await prisma.project.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Projects and only return the `id`
   * const projectWithIdOnly = await prisma.project.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProjectCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProjectCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Project.
   * @param {ProjectDeleteArgs} args - Arguments to delete one Project.
   * @example
   * // Delete one Project
   * const Project = await prisma.project.delete({
   *   where: {
   *     // ... filter to delete one Project
   *   }
   * })
   * 
   */
  delete<T extends ProjectDeleteArgs>(args: Prisma.SelectSubset<T, ProjectDeleteArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Project.
   * @param {ProjectUpdateArgs} args - Arguments to update one Project.
   * @example
   * // Update one Project
   * const project = await prisma.project.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProjectUpdateArgs>(args: Prisma.SelectSubset<T, ProjectUpdateArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Projects.
   * @param {ProjectDeleteManyArgs} args - Arguments to filter Projects to delete.
   * @example
   * // Delete a few Projects
   * const { count } = await prisma.project.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProjectDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProjectDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Projects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Projects
   * const project = await prisma.project.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProjectUpdateManyArgs>(args: Prisma.SelectSubset<T, ProjectUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Projects and returns the data updated in the database.
   * @param {ProjectUpdateManyAndReturnArgs} args - Arguments to update many Projects.
   * @example
   * // Update many Projects
   * const project = await prisma.project.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Projects and only return the `id`
   * const projectWithIdOnly = await prisma.project.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProjectUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProjectUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Project.
   * @param {ProjectUpsertArgs} args - Arguments to update or create a Project.
   * @example
   * // Update or create a Project
   * const project = await prisma.project.upsert({
   *   create: {
   *     // ... data to create a Project
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Project we want to update
   *   }
   * })
   */
  upsert<T extends ProjectUpsertArgs>(args: Prisma.SelectSubset<T, ProjectUpsertArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Projects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectCountArgs} args - Arguments to filter Projects to count.
   * @example
   * // Count the number of Projects
   * const count = await prisma.project.count({
   *   where: {
   *     // ... the filter for the Projects we want to count
   *   }
   * })
  **/
  count<T extends ProjectCountArgs>(
    args?: Prisma.Subset<T, ProjectCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProjectCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Project.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProjectAggregateArgs>(args: Prisma.Subset<T, ProjectAggregateArgs>): Prisma.PrismaPromise<GetProjectAggregateType<T>>

  /**
   * Group by Project.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProjectGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProjectGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProjectGroupByArgs['orderBy'] }
      : { orderBy?: ProjectGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProjectGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProjectGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Project model
 */
readonly fields: ProjectFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Project.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProjectClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Type<T extends Prisma.ProjectTypeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProjectTypeDefaultArgs<ExtArgs>>): Prisma.Prisma__ProjectTypeClient<runtime.Types.Result.GetResult<Prisma.$ProjectTypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  Document<T extends Prisma.Project$DocumentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Project$DocumentArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DocumentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  Meeting<T extends Prisma.Project$MeetingArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Project$MeetingArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MeetingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  Milestone<T extends Prisma.Project$MilestoneArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Project$MilestoneArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MilestonePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  ProjectGroup<T extends Prisma.ProjectGroupDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProjectGroupDefaultArgs<ExtArgs>>): Prisma.Prisma__ProjectGroupClient<runtime.Types.Result.GetResult<Prisma.$ProjectGroupPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  FacultyProfile<T extends Prisma.Project$FacultyProfileArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Project$FacultyProfileArgs<ExtArgs>>): Prisma.Prisma__FacultyProfileClient<runtime.Types.Result.GetResult<Prisma.$FacultyProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Project model
 */
export interface ProjectFieldRefs {
  readonly id: Prisma.FieldRef<"Project", 'String'>
  readonly title: Prisma.FieldRef<"Project", 'String'>
  readonly description: Prisma.FieldRef<"Project", 'String'>
  readonly typeId: Prisma.FieldRef<"Project", 'String'>
  readonly status: Prisma.FieldRef<"Project", 'ProjectStatus'>
  readonly groupId: Prisma.FieldRef<"Project", 'String'>
  readonly guideId: Prisma.FieldRef<"Project", 'String'>
  readonly createdAt: Prisma.FieldRef<"Project", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Project", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Project findUnique
 */
export type ProjectFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * Filter, which Project to fetch.
   */
  where: Prisma.ProjectWhereUniqueInput
}

/**
 * Project findUniqueOrThrow
 */
export type ProjectFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * Filter, which Project to fetch.
   */
  where: Prisma.ProjectWhereUniqueInput
}

/**
 * Project findFirst
 */
export type ProjectFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * Filter, which Project to fetch.
   */
  where?: Prisma.ProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Projects to fetch.
   */
  orderBy?: Prisma.ProjectOrderByWithRelationInput | Prisma.ProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Projects.
   */
  cursor?: Prisma.ProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Projects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Projects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Projects.
   */
  distinct?: Prisma.ProjectScalarFieldEnum | Prisma.ProjectScalarFieldEnum[]
}

/**
 * Project findFirstOrThrow
 */
export type ProjectFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * Filter, which Project to fetch.
   */
  where?: Prisma.ProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Projects to fetch.
   */
  orderBy?: Prisma.ProjectOrderByWithRelationInput | Prisma.ProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Projects.
   */
  cursor?: Prisma.ProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Projects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Projects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Projects.
   */
  distinct?: Prisma.ProjectScalarFieldEnum | Prisma.ProjectScalarFieldEnum[]
}

/**
 * Project findMany
 */
export type ProjectFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * Filter, which Projects to fetch.
   */
  where?: Prisma.ProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Projects to fetch.
   */
  orderBy?: Prisma.ProjectOrderByWithRelationInput | Prisma.ProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Projects.
   */
  cursor?: Prisma.ProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Projects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Projects.
   */
  skip?: number
  distinct?: Prisma.ProjectScalarFieldEnum | Prisma.ProjectScalarFieldEnum[]
}

/**
 * Project create
 */
export type ProjectCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * The data needed to create a Project.
   */
  data: Prisma.XOR<Prisma.ProjectCreateInput, Prisma.ProjectUncheckedCreateInput>
}

/**
 * Project createMany
 */
export type ProjectCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Projects.
   */
  data: Prisma.ProjectCreateManyInput | Prisma.ProjectCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Project createManyAndReturn
 */
export type ProjectCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * The data used to create many Projects.
   */
  data: Prisma.ProjectCreateManyInput | Prisma.ProjectCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Project update
 */
export type ProjectUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * The data needed to update a Project.
   */
  data: Prisma.XOR<Prisma.ProjectUpdateInput, Prisma.ProjectUncheckedUpdateInput>
  /**
   * Choose, which Project to update.
   */
  where: Prisma.ProjectWhereUniqueInput
}

/**
 * Project updateMany
 */
export type ProjectUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Projects.
   */
  data: Prisma.XOR<Prisma.ProjectUpdateManyMutationInput, Prisma.ProjectUncheckedUpdateManyInput>
  /**
   * Filter which Projects to update
   */
  where?: Prisma.ProjectWhereInput
  /**
   * Limit how many Projects to update.
   */
  limit?: number
}

/**
 * Project updateManyAndReturn
 */
export type ProjectUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * The data used to update Projects.
   */
  data: Prisma.XOR<Prisma.ProjectUpdateManyMutationInput, Prisma.ProjectUncheckedUpdateManyInput>
  /**
   * Filter which Projects to update
   */
  where?: Prisma.ProjectWhereInput
  /**
   * Limit how many Projects to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Project upsert
 */
export type ProjectUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * The filter to search for the Project to update in case it exists.
   */
  where: Prisma.ProjectWhereUniqueInput
  /**
   * In case the Project found by the `where` argument doesn't exist, create a new Project with this data.
   */
  create: Prisma.XOR<Prisma.ProjectCreateInput, Prisma.ProjectUncheckedCreateInput>
  /**
   * In case the Project was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProjectUpdateInput, Prisma.ProjectUncheckedUpdateInput>
}

/**
 * Project delete
 */
export type ProjectDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
  /**
   * Filter which Project to delete.
   */
  where: Prisma.ProjectWhereUniqueInput
}

/**
 * Project deleteMany
 */
export type ProjectDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Projects to delete
   */
  where?: Prisma.ProjectWhereInput
  /**
   * Limit how many Projects to delete.
   */
  limit?: number
}

/**
 * Project.Document
 */
export type Project$DocumentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Document
   */
  select?: Prisma.DocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Document
   */
  omit?: Prisma.DocumentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentInclude<ExtArgs> | null
  where?: Prisma.DocumentWhereInput
  orderBy?: Prisma.DocumentOrderByWithRelationInput | Prisma.DocumentOrderByWithRelationInput[]
  cursor?: Prisma.DocumentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DocumentScalarFieldEnum | Prisma.DocumentScalarFieldEnum[]
}

/**
 * Project.Meeting
 */
export type Project$MeetingArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Meeting
   */
  select?: Prisma.MeetingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Meeting
   */
  omit?: Prisma.MeetingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MeetingInclude<ExtArgs> | null
  where?: Prisma.MeetingWhereInput
  orderBy?: Prisma.MeetingOrderByWithRelationInput | Prisma.MeetingOrderByWithRelationInput[]
  cursor?: Prisma.MeetingWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MeetingScalarFieldEnum | Prisma.MeetingScalarFieldEnum[]
}

/**
 * Project.Milestone
 */
export type Project$MilestoneArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Milestone
   */
  select?: Prisma.MilestoneSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Milestone
   */
  omit?: Prisma.MilestoneOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MilestoneInclude<ExtArgs> | null
  where?: Prisma.MilestoneWhereInput
  orderBy?: Prisma.MilestoneOrderByWithRelationInput | Prisma.MilestoneOrderByWithRelationInput[]
  cursor?: Prisma.MilestoneWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MilestoneScalarFieldEnum | Prisma.MilestoneScalarFieldEnum[]
}

/**
 * Project.FacultyProfile
 */
export type Project$FacultyProfileArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FacultyProfile
   */
  select?: Prisma.FacultyProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FacultyProfile
   */
  omit?: Prisma.FacultyProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FacultyProfileInclude<ExtArgs> | null
  where?: Prisma.FacultyProfileWhereInput
}

/**
 * Project without action
 */
export type ProjectDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Project
   */
  select?: Prisma.ProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Project
   */
  omit?: Prisma.ProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectInclude<ExtArgs> | null
}
