
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `StudentProfile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model StudentProfile
 * 
 */
export type StudentProfileModel = runtime.Types.Result.DefaultSelection<Prisma.$StudentProfilePayload>

export type AggregateStudentProfile = {
  _count: StudentProfileCountAggregateOutputType | null
  _min: StudentProfileMinAggregateOutputType | null
  _max: StudentProfileMaxAggregateOutputType | null
}

export type StudentProfileMinAggregateOutputType = {
  id: string | null
  userId: string | null
  idNumber: string | null
  department: string | null
  batch: string | null
  groupId: string | null
  isLeader: boolean | null
}

export type StudentProfileMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  idNumber: string | null
  department: string | null
  batch: string | null
  groupId: string | null
  isLeader: boolean | null
}

export type StudentProfileCountAggregateOutputType = {
  id: number
  userId: number
  idNumber: number
  department: number
  batch: number
  groupId: number
  isLeader: number
  _all: number
}


export type StudentProfileMinAggregateInputType = {
  id?: true
  userId?: true
  idNumber?: true
  department?: true
  batch?: true
  groupId?: true
  isLeader?: true
}

export type StudentProfileMaxAggregateInputType = {
  id?: true
  userId?: true
  idNumber?: true
  department?: true
  batch?: true
  groupId?: true
  isLeader?: true
}

export type StudentProfileCountAggregateInputType = {
  id?: true
  userId?: true
  idNumber?: true
  department?: true
  batch?: true
  groupId?: true
  isLeader?: true
  _all?: true
}

export type StudentProfileAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StudentProfile to aggregate.
   */
  where?: Prisma.StudentProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StudentProfiles to fetch.
   */
  orderBy?: Prisma.StudentProfileOrderByWithRelationInput | Prisma.StudentProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StudentProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StudentProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StudentProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned StudentProfiles
  **/
  _count?: true | StudentProfileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StudentProfileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StudentProfileMaxAggregateInputType
}

export type GetStudentProfileAggregateType<T extends StudentProfileAggregateArgs> = {
      [P in keyof T & keyof AggregateStudentProfile]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStudentProfile[P]>
    : Prisma.GetScalarType<T[P], AggregateStudentProfile[P]>
}




export type StudentProfileGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StudentProfileWhereInput
  orderBy?: Prisma.StudentProfileOrderByWithAggregationInput | Prisma.StudentProfileOrderByWithAggregationInput[]
  by: Prisma.StudentProfileScalarFieldEnum[] | Prisma.StudentProfileScalarFieldEnum
  having?: Prisma.StudentProfileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StudentProfileCountAggregateInputType | true
  _min?: StudentProfileMinAggregateInputType
  _max?: StudentProfileMaxAggregateInputType
}

export type StudentProfileGroupByOutputType = {
  id: string
  userId: string
  idNumber: string
  department: string
  batch: string
  groupId: string | null
  isLeader: boolean
  _count: StudentProfileCountAggregateOutputType | null
  _min: StudentProfileMinAggregateOutputType | null
  _max: StudentProfileMaxAggregateOutputType | null
}

type GetStudentProfileGroupByPayload<T extends StudentProfileGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StudentProfileGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StudentProfileGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StudentProfileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StudentProfileGroupByOutputType[P]>
      }
    >
  >



export type StudentProfileWhereInput = {
  AND?: Prisma.StudentProfileWhereInput | Prisma.StudentProfileWhereInput[]
  OR?: Prisma.StudentProfileWhereInput[]
  NOT?: Prisma.StudentProfileWhereInput | Prisma.StudentProfileWhereInput[]
  id?: Prisma.StringFilter<"StudentProfile"> | string
  userId?: Prisma.StringFilter<"StudentProfile"> | string
  idNumber?: Prisma.StringFilter<"StudentProfile"> | string
  department?: Prisma.StringFilter<"StudentProfile"> | string
  batch?: Prisma.StringFilter<"StudentProfile"> | string
  groupId?: Prisma.StringNullableFilter<"StudentProfile"> | string | null
  isLeader?: Prisma.BoolFilter<"StudentProfile"> | boolean
  ProjectGroup?: Prisma.XOR<Prisma.ProjectGroupNullableScalarRelationFilter, Prisma.ProjectGroupWhereInput> | null
  User?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  Attendance?: Prisma.MeetingAttendanceListRelationFilter
}

export type StudentProfileOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  idNumber?: Prisma.SortOrder
  department?: Prisma.SortOrder
  batch?: Prisma.SortOrder
  groupId?: Prisma.SortOrderInput | Prisma.SortOrder
  isLeader?: Prisma.SortOrder
  ProjectGroup?: Prisma.ProjectGroupOrderByWithRelationInput
  User?: Prisma.UserOrderByWithRelationInput
  Attendance?: Prisma.MeetingAttendanceOrderByRelationAggregateInput
}

export type StudentProfileWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId?: string
  idNumber?: string
  AND?: Prisma.StudentProfileWhereInput | Prisma.StudentProfileWhereInput[]
  OR?: Prisma.StudentProfileWhereInput[]
  NOT?: Prisma.StudentProfileWhereInput | Prisma.StudentProfileWhereInput[]
  department?: Prisma.StringFilter<"StudentProfile"> | string
  batch?: Prisma.StringFilter<"StudentProfile"> | string
  groupId?: Prisma.StringNullableFilter<"StudentProfile"> | string | null
  isLeader?: Prisma.BoolFilter<"StudentProfile"> | boolean
  ProjectGroup?: Prisma.XOR<Prisma.ProjectGroupNullableScalarRelationFilter, Prisma.ProjectGroupWhereInput> | null
  User?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  Attendance?: Prisma.MeetingAttendanceListRelationFilter
}, "id" | "userId" | "idNumber">

export type StudentProfileOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  idNumber?: Prisma.SortOrder
  department?: Prisma.SortOrder
  batch?: Prisma.SortOrder
  groupId?: Prisma.SortOrderInput | Prisma.SortOrder
  isLeader?: Prisma.SortOrder
  _count?: Prisma.StudentProfileCountOrderByAggregateInput
  _max?: Prisma.StudentProfileMaxOrderByAggregateInput
  _min?: Prisma.StudentProfileMinOrderByAggregateInput
}

export type StudentProfileScalarWhereWithAggregatesInput = {
  AND?: Prisma.StudentProfileScalarWhereWithAggregatesInput | Prisma.StudentProfileScalarWhereWithAggregatesInput[]
  OR?: Prisma.StudentProfileScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StudentProfileScalarWhereWithAggregatesInput | Prisma.StudentProfileScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"StudentProfile"> | string
  userId?: Prisma.StringWithAggregatesFilter<"StudentProfile"> | string
  idNumber?: Prisma.StringWithAggregatesFilter<"StudentProfile"> | string
  department?: Prisma.StringWithAggregatesFilter<"StudentProfile"> | string
  batch?: Prisma.StringWithAggregatesFilter<"StudentProfile"> | string
  groupId?: Prisma.StringNullableWithAggregatesFilter<"StudentProfile"> | string | null
  isLeader?: Prisma.BoolWithAggregatesFilter<"StudentProfile"> | boolean
}

export type StudentProfileCreateInput = {
  id: string
  idNumber: string
  department: string
  batch: string
  isLeader?: boolean
  ProjectGroup?: Prisma.ProjectGroupCreateNestedOneWithoutStudentProfileInput
  User: Prisma.UserCreateNestedOneWithoutStudentProfileInput
  Attendance?: Prisma.MeetingAttendanceCreateNestedManyWithoutStudentInput
}

export type StudentProfileUncheckedCreateInput = {
  id: string
  userId: string
  idNumber: string
  department: string
  batch: string
  groupId?: string | null
  isLeader?: boolean
  Attendance?: Prisma.MeetingAttendanceUncheckedCreateNestedManyWithoutStudentInput
}

export type StudentProfileUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idNumber?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  batch?: Prisma.StringFieldUpdateOperationsInput | string
  isLeader?: Prisma.BoolFieldUpdateOperationsInput | boolean
  ProjectGroup?: Prisma.ProjectGroupUpdateOneWithoutStudentProfileNestedInput
  User?: Prisma.UserUpdateOneRequiredWithoutStudentProfileNestedInput
  Attendance?: Prisma.MeetingAttendanceUpdateManyWithoutStudentNestedInput
}

export type StudentProfileUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  idNumber?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  batch?: Prisma.StringFieldUpdateOperationsInput | string
  groupId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isLeader?: Prisma.BoolFieldUpdateOperationsInput | boolean
  Attendance?: Prisma.MeetingAttendanceUncheckedUpdateManyWithoutStudentNestedInput
}

export type StudentProfileCreateManyInput = {
  id: string
  userId: string
  idNumber: string
  department: string
  batch: string
  groupId?: string | null
  isLeader?: boolean
}

export type StudentProfileUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idNumber?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  batch?: Prisma.StringFieldUpdateOperationsInput | string
  isLeader?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type StudentProfileUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  idNumber?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  batch?: Prisma.StringFieldUpdateOperationsInput | string
  groupId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isLeader?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type StudentProfileScalarRelationFilter = {
  is?: Prisma.StudentProfileWhereInput
  isNot?: Prisma.StudentProfileWhereInput
}

export type StudentProfileListRelationFilter = {
  every?: Prisma.StudentProfileWhereInput
  some?: Prisma.StudentProfileWhereInput
  none?: Prisma.StudentProfileWhereInput
}

export type StudentProfileOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StudentProfileCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  idNumber?: Prisma.SortOrder
  department?: Prisma.SortOrder
  batch?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  isLeader?: Prisma.SortOrder
}

export type StudentProfileMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  idNumber?: Prisma.SortOrder
  department?: Prisma.SortOrder
  batch?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  isLeader?: Prisma.SortOrder
}

export type StudentProfileMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  idNumber?: Prisma.SortOrder
  department?: Prisma.SortOrder
  batch?: Prisma.SortOrder
  groupId?: Prisma.SortOrder
  isLeader?: Prisma.SortOrder
}

export type StudentProfileNullableScalarRelationFilter = {
  is?: Prisma.StudentProfileWhereInput | null
  isNot?: Prisma.StudentProfileWhereInput | null
}

export type StudentProfileCreateNestedOneWithoutAttendanceInput = {
  create?: Prisma.XOR<Prisma.StudentProfileCreateWithoutAttendanceInput, Prisma.StudentProfileUncheckedCreateWithoutAttendanceInput>
  connectOrCreate?: Prisma.StudentProfileCreateOrConnectWithoutAttendanceInput
  connect?: Prisma.StudentProfileWhereUniqueInput
}

export type StudentProfileUpdateOneRequiredWithoutAttendanceNestedInput = {
  create?: Prisma.XOR<Prisma.StudentProfileCreateWithoutAttendanceInput, Prisma.StudentProfileUncheckedCreateWithoutAttendanceInput>
  connectOrCreate?: Prisma.StudentProfileCreateOrConnectWithoutAttendanceInput
  upsert?: Prisma.StudentProfileUpsertWithoutAttendanceInput
  connect?: Prisma.StudentProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StudentProfileUpdateToOneWithWhereWithoutAttendanceInput, Prisma.StudentProfileUpdateWithoutAttendanceInput>, Prisma.StudentProfileUncheckedUpdateWithoutAttendanceInput>
}

export type StudentProfileCreateNestedManyWithoutProjectGroupInput = {
  create?: Prisma.XOR<Prisma.StudentProfileCreateWithoutProjectGroupInput, Prisma.StudentProfileUncheckedCreateWithoutProjectGroupInput> | Prisma.StudentProfileCreateWithoutProjectGroupInput[] | Prisma.StudentProfileUncheckedCreateWithoutProjectGroupInput[]
  connectOrCreate?: Prisma.StudentProfileCreateOrConnectWithoutProjectGroupInput | Prisma.StudentProfileCreateOrConnectWithoutProjectGroupInput[]
  createMany?: Prisma.StudentProfileCreateManyProjectGroupInputEnvelope
  connect?: Prisma.StudentProfileWhereUniqueInput | Prisma.StudentProfileWhereUniqueInput[]
}

export type StudentProfileUncheckedCreateNestedManyWithoutProjectGroupInput = {
  create?: Prisma.XOR<Prisma.StudentProfileCreateWithoutProjectGroupInput, Prisma.StudentProfileUncheckedCreateWithoutProjectGroupInput> | Prisma.StudentProfileCreateWithoutProjectGroupInput[] | Prisma.StudentProfileUncheckedCreateWithoutProjectGroupInput[]
  connectOrCreate?: Prisma.StudentProfileCreateOrConnectWithoutProjectGroupInput | Prisma.StudentProfileCreateOrConnectWithoutProjectGroupInput[]
  createMany?: Prisma.StudentProfileCreateManyProjectGroupInputEnvelope
  connect?: Prisma.StudentProfileWhereUniqueInput | Prisma.StudentProfileWhereUniqueInput[]
}

export type StudentProfileUpdateManyWithoutProjectGroupNestedInput = {
  create?: Prisma.XOR<Prisma.StudentProfileCreateWithoutProjectGroupInput, Prisma.StudentProfileUncheckedCreateWithoutProjectGroupInput> | Prisma.StudentProfileCreateWithoutProjectGroupInput[] | Prisma.StudentProfileUncheckedCreateWithoutProjectGroupInput[]
  connectOrCreate?: Prisma.StudentProfileCreateOrConnectWithoutProjectGroupInput | Prisma.StudentProfileCreateOrConnectWithoutProjectGroupInput[]
  upsert?: Prisma.StudentProfileUpsertWithWhereUniqueWithoutProjectGroupInput | Prisma.StudentProfileUpsertWithWhereUniqueWithoutProjectGroupInput[]
  createMany?: Prisma.StudentProfileCreateManyProjectGroupInputEnvelope
  set?: Prisma.StudentProfileWhereUniqueInput | Prisma.StudentProfileWhereUniqueInput[]
  disconnect?: Prisma.StudentProfileWhereUniqueInput | Prisma.StudentProfileWhereUniqueInput[]
  delete?: Prisma.StudentProfileWhereUniqueInput | Prisma.StudentProfileWhereUniqueInput[]
  connect?: Prisma.StudentProfileWhereUniqueInput | Prisma.StudentProfileWhereUniqueInput[]
  update?: Prisma.StudentProfileUpdateWithWhereUniqueWithoutProjectGroupInput | Prisma.StudentProfileUpdateWithWhereUniqueWithoutProjectGroupInput[]
  updateMany?: Prisma.StudentProfileUpdateManyWithWhereWithoutProjectGroupInput | Prisma.StudentProfileUpdateManyWithWhereWithoutProjectGroupInput[]
  deleteMany?: Prisma.StudentProfileScalarWhereInput | Prisma.StudentProfileScalarWhereInput[]
}

export type StudentProfileUncheckedUpdateManyWithoutProjectGroupNestedInput = {
  create?: Prisma.XOR<Prisma.StudentProfileCreateWithoutProjectGroupInput, Prisma.StudentProfileUncheckedCreateWithoutProjectGroupInput> | Prisma.StudentProfileCreateWithoutProjectGroupInput[] | Prisma.StudentProfileUncheckedCreateWithoutProjectGroupInput[]
  connectOrCreate?: Prisma.StudentProfileCreateOrConnectWithoutProjectGroupInput | Prisma.StudentProfileCreateOrConnectWithoutProjectGroupInput[]
  upsert?: Prisma.StudentProfileUpsertWithWhereUniqueWithoutProjectGroupInput | Prisma.StudentProfileUpsertWithWhereUniqueWithoutProjectGroupInput[]
  createMany?: Prisma.StudentProfileCreateManyProjectGroupInputEnvelope
  set?: Prisma.StudentProfileWhereUniqueInput | Prisma.StudentProfileWhereUniqueInput[]
  disconnect?: Prisma.StudentProfileWhereUniqueInput | Prisma.StudentProfileWhereUniqueInput[]
  delete?: Prisma.StudentProfileWhereUniqueInput | Prisma.StudentProfileWhereUniqueInput[]
  connect?: Prisma.StudentProfileWhereUniqueInput | Prisma.StudentProfileWhereUniqueInput[]
  update?: Prisma.StudentProfileUpdateWithWhereUniqueWithoutProjectGroupInput | Prisma.StudentProfileUpdateWithWhereUniqueWithoutProjectGroupInput[]
  updateMany?: Prisma.StudentProfileUpdateManyWithWhereWithoutProjectGroupInput | Prisma.StudentProfileUpdateManyWithWhereWithoutProjectGroupInput[]
  deleteMany?: Prisma.StudentProfileScalarWhereInput | Prisma.StudentProfileScalarWhereInput[]
}

export type StudentProfileCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.StudentProfileCreateWithoutUserInput, Prisma.StudentProfileUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.StudentProfileCreateOrConnectWithoutUserInput
  connect?: Prisma.StudentProfileWhereUniqueInput
}

export type StudentProfileUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.StudentProfileCreateWithoutUserInput, Prisma.StudentProfileUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.StudentProfileCreateOrConnectWithoutUserInput
  connect?: Prisma.StudentProfileWhereUniqueInput
}

export type StudentProfileUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.StudentProfileCreateWithoutUserInput, Prisma.StudentProfileUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.StudentProfileCreateOrConnectWithoutUserInput
  upsert?: Prisma.StudentProfileUpsertWithoutUserInput
  disconnect?: Prisma.StudentProfileWhereInput | boolean
  delete?: Prisma.StudentProfileWhereInput | boolean
  connect?: Prisma.StudentProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StudentProfileUpdateToOneWithWhereWithoutUserInput, Prisma.StudentProfileUpdateWithoutUserInput>, Prisma.StudentProfileUncheckedUpdateWithoutUserInput>
}

export type StudentProfileUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.StudentProfileCreateWithoutUserInput, Prisma.StudentProfileUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.StudentProfileCreateOrConnectWithoutUserInput
  upsert?: Prisma.StudentProfileUpsertWithoutUserInput
  disconnect?: Prisma.StudentProfileWhereInput | boolean
  delete?: Prisma.StudentProfileWhereInput | boolean
  connect?: Prisma.StudentProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.StudentProfileUpdateToOneWithWhereWithoutUserInput, Prisma.StudentProfileUpdateWithoutUserInput>, Prisma.StudentProfileUncheckedUpdateWithoutUserInput>
}

export type StudentProfileCreateWithoutAttendanceInput = {
  id: string
  idNumber: string
  department: string
  batch: string
  isLeader?: boolean
  ProjectGroup?: Prisma.ProjectGroupCreateNestedOneWithoutStudentProfileInput
  User: Prisma.UserCreateNestedOneWithoutStudentProfileInput
}

export type StudentProfileUncheckedCreateWithoutAttendanceInput = {
  id: string
  userId: string
  idNumber: string
  department: string
  batch: string
  groupId?: string | null
  isLeader?: boolean
}

export type StudentProfileCreateOrConnectWithoutAttendanceInput = {
  where: Prisma.StudentProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.StudentProfileCreateWithoutAttendanceInput, Prisma.StudentProfileUncheckedCreateWithoutAttendanceInput>
}

export type StudentProfileUpsertWithoutAttendanceInput = {
  update: Prisma.XOR<Prisma.StudentProfileUpdateWithoutAttendanceInput, Prisma.StudentProfileUncheckedUpdateWithoutAttendanceInput>
  create: Prisma.XOR<Prisma.StudentProfileCreateWithoutAttendanceInput, Prisma.StudentProfileUncheckedCreateWithoutAttendanceInput>
  where?: Prisma.StudentProfileWhereInput
}

export type StudentProfileUpdateToOneWithWhereWithoutAttendanceInput = {
  where?: Prisma.StudentProfileWhereInput
  data: Prisma.XOR<Prisma.StudentProfileUpdateWithoutAttendanceInput, Prisma.StudentProfileUncheckedUpdateWithoutAttendanceInput>
}

export type StudentProfileUpdateWithoutAttendanceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idNumber?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  batch?: Prisma.StringFieldUpdateOperationsInput | string
  isLeader?: Prisma.BoolFieldUpdateOperationsInput | boolean
  ProjectGroup?: Prisma.ProjectGroupUpdateOneWithoutStudentProfileNestedInput
  User?: Prisma.UserUpdateOneRequiredWithoutStudentProfileNestedInput
}

export type StudentProfileUncheckedUpdateWithoutAttendanceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  idNumber?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  batch?: Prisma.StringFieldUpdateOperationsInput | string
  groupId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isLeader?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type StudentProfileCreateWithoutProjectGroupInput = {
  id: string
  idNumber: string
  department: string
  batch: string
  isLeader?: boolean
  User: Prisma.UserCreateNestedOneWithoutStudentProfileInput
  Attendance?: Prisma.MeetingAttendanceCreateNestedManyWithoutStudentInput
}

export type StudentProfileUncheckedCreateWithoutProjectGroupInput = {
  id: string
  userId: string
  idNumber: string
  department: string
  batch: string
  isLeader?: boolean
  Attendance?: Prisma.MeetingAttendanceUncheckedCreateNestedManyWithoutStudentInput
}

export type StudentProfileCreateOrConnectWithoutProjectGroupInput = {
  where: Prisma.StudentProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.StudentProfileCreateWithoutProjectGroupInput, Prisma.StudentProfileUncheckedCreateWithoutProjectGroupInput>
}

export type StudentProfileCreateManyProjectGroupInputEnvelope = {
  data: Prisma.StudentProfileCreateManyProjectGroupInput | Prisma.StudentProfileCreateManyProjectGroupInput[]
  skipDuplicates?: boolean
}

export type StudentProfileUpsertWithWhereUniqueWithoutProjectGroupInput = {
  where: Prisma.StudentProfileWhereUniqueInput
  update: Prisma.XOR<Prisma.StudentProfileUpdateWithoutProjectGroupInput, Prisma.StudentProfileUncheckedUpdateWithoutProjectGroupInput>
  create: Prisma.XOR<Prisma.StudentProfileCreateWithoutProjectGroupInput, Prisma.StudentProfileUncheckedCreateWithoutProjectGroupInput>
}

export type StudentProfileUpdateWithWhereUniqueWithoutProjectGroupInput = {
  where: Prisma.StudentProfileWhereUniqueInput
  data: Prisma.XOR<Prisma.StudentProfileUpdateWithoutProjectGroupInput, Prisma.StudentProfileUncheckedUpdateWithoutProjectGroupInput>
}

export type StudentProfileUpdateManyWithWhereWithoutProjectGroupInput = {
  where: Prisma.StudentProfileScalarWhereInput
  data: Prisma.XOR<Prisma.StudentProfileUpdateManyMutationInput, Prisma.StudentProfileUncheckedUpdateManyWithoutProjectGroupInput>
}

export type StudentProfileScalarWhereInput = {
  AND?: Prisma.StudentProfileScalarWhereInput | Prisma.StudentProfileScalarWhereInput[]
  OR?: Prisma.StudentProfileScalarWhereInput[]
  NOT?: Prisma.StudentProfileScalarWhereInput | Prisma.StudentProfileScalarWhereInput[]
  id?: Prisma.StringFilter<"StudentProfile"> | string
  userId?: Prisma.StringFilter<"StudentProfile"> | string
  idNumber?: Prisma.StringFilter<"StudentProfile"> | string
  department?: Prisma.StringFilter<"StudentProfile"> | string
  batch?: Prisma.StringFilter<"StudentProfile"> | string
  groupId?: Prisma.StringNullableFilter<"StudentProfile"> | string | null
  isLeader?: Prisma.BoolFilter<"StudentProfile"> | boolean
}

export type StudentProfileCreateWithoutUserInput = {
  id: string
  idNumber: string
  department: string
  batch: string
  isLeader?: boolean
  ProjectGroup?: Prisma.ProjectGroupCreateNestedOneWithoutStudentProfileInput
  Attendance?: Prisma.MeetingAttendanceCreateNestedManyWithoutStudentInput
}

export type StudentProfileUncheckedCreateWithoutUserInput = {
  id: string
  idNumber: string
  department: string
  batch: string
  groupId?: string | null
  isLeader?: boolean
  Attendance?: Prisma.MeetingAttendanceUncheckedCreateNestedManyWithoutStudentInput
}

export type StudentProfileCreateOrConnectWithoutUserInput = {
  where: Prisma.StudentProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.StudentProfileCreateWithoutUserInput, Prisma.StudentProfileUncheckedCreateWithoutUserInput>
}

export type StudentProfileUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.StudentProfileUpdateWithoutUserInput, Prisma.StudentProfileUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.StudentProfileCreateWithoutUserInput, Prisma.StudentProfileUncheckedCreateWithoutUserInput>
  where?: Prisma.StudentProfileWhereInput
}

export type StudentProfileUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.StudentProfileWhereInput
  data: Prisma.XOR<Prisma.StudentProfileUpdateWithoutUserInput, Prisma.StudentProfileUncheckedUpdateWithoutUserInput>
}

export type StudentProfileUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idNumber?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  batch?: Prisma.StringFieldUpdateOperationsInput | string
  isLeader?: Prisma.BoolFieldUpdateOperationsInput | boolean
  ProjectGroup?: Prisma.ProjectGroupUpdateOneWithoutStudentProfileNestedInput
  Attendance?: Prisma.MeetingAttendanceUpdateManyWithoutStudentNestedInput
}

export type StudentProfileUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idNumber?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  batch?: Prisma.StringFieldUpdateOperationsInput | string
  groupId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isLeader?: Prisma.BoolFieldUpdateOperationsInput | boolean
  Attendance?: Prisma.MeetingAttendanceUncheckedUpdateManyWithoutStudentNestedInput
}

export type StudentProfileCreateManyProjectGroupInput = {
  id: string
  userId: string
  idNumber: string
  department: string
  batch: string
  isLeader?: boolean
}

export type StudentProfileUpdateWithoutProjectGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idNumber?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  batch?: Prisma.StringFieldUpdateOperationsInput | string
  isLeader?: Prisma.BoolFieldUpdateOperationsInput | boolean
  User?: Prisma.UserUpdateOneRequiredWithoutStudentProfileNestedInput
  Attendance?: Prisma.MeetingAttendanceUpdateManyWithoutStudentNestedInput
}

export type StudentProfileUncheckedUpdateWithoutProjectGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  idNumber?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  batch?: Prisma.StringFieldUpdateOperationsInput | string
  isLeader?: Prisma.BoolFieldUpdateOperationsInput | boolean
  Attendance?: Prisma.MeetingAttendanceUncheckedUpdateManyWithoutStudentNestedInput
}

export type StudentProfileUncheckedUpdateManyWithoutProjectGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  idNumber?: Prisma.StringFieldUpdateOperationsInput | string
  department?: Prisma.StringFieldUpdateOperationsInput | string
  batch?: Prisma.StringFieldUpdateOperationsInput | string
  isLeader?: Prisma.BoolFieldUpdateOperationsInput | boolean
}


/**
 * Count Type StudentProfileCountOutputType
 */

export type StudentProfileCountOutputType = {
  Attendance: number
}

export type StudentProfileCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Attendance?: boolean | StudentProfileCountOutputTypeCountAttendanceArgs
}

/**
 * StudentProfileCountOutputType without action
 */
export type StudentProfileCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentProfileCountOutputType
   */
  select?: Prisma.StudentProfileCountOutputTypeSelect<ExtArgs> | null
}

/**
 * StudentProfileCountOutputType without action
 */
export type StudentProfileCountOutputTypeCountAttendanceArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MeetingAttendanceWhereInput
}


export type StudentProfileSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  idNumber?: boolean
  department?: boolean
  batch?: boolean
  groupId?: boolean
  isLeader?: boolean
  ProjectGroup?: boolean | Prisma.StudentProfile$ProjectGroupArgs<ExtArgs>
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  Attendance?: boolean | Prisma.StudentProfile$AttendanceArgs<ExtArgs>
  _count?: boolean | Prisma.StudentProfileCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["studentProfile"]>

export type StudentProfileSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  idNumber?: boolean
  department?: boolean
  batch?: boolean
  groupId?: boolean
  isLeader?: boolean
  ProjectGroup?: boolean | Prisma.StudentProfile$ProjectGroupArgs<ExtArgs>
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["studentProfile"]>

export type StudentProfileSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  idNumber?: boolean
  department?: boolean
  batch?: boolean
  groupId?: boolean
  isLeader?: boolean
  ProjectGroup?: boolean | Prisma.StudentProfile$ProjectGroupArgs<ExtArgs>
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["studentProfile"]>

export type StudentProfileSelectScalar = {
  id?: boolean
  userId?: boolean
  idNumber?: boolean
  department?: boolean
  batch?: boolean
  groupId?: boolean
  isLeader?: boolean
}

export type StudentProfileOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "idNumber" | "department" | "batch" | "groupId" | "isLeader", ExtArgs["result"]["studentProfile"]>
export type StudentProfileInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ProjectGroup?: boolean | Prisma.StudentProfile$ProjectGroupArgs<ExtArgs>
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  Attendance?: boolean | Prisma.StudentProfile$AttendanceArgs<ExtArgs>
  _count?: boolean | Prisma.StudentProfileCountOutputTypeDefaultArgs<ExtArgs>
}
export type StudentProfileIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ProjectGroup?: boolean | Prisma.StudentProfile$ProjectGroupArgs<ExtArgs>
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type StudentProfileIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ProjectGroup?: boolean | Prisma.StudentProfile$ProjectGroupArgs<ExtArgs>
  User?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $StudentProfilePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "StudentProfile"
  objects: {
    ProjectGroup: Prisma.$ProjectGroupPayload<ExtArgs> | null
    User: Prisma.$UserPayload<ExtArgs>
    Attendance: Prisma.$MeetingAttendancePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    idNumber: string
    department: string
    batch: string
    groupId: string | null
    isLeader: boolean
  }, ExtArgs["result"]["studentProfile"]>
  composites: {}
}

export type StudentProfileGetPayload<S extends boolean | null | undefined | StudentProfileDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StudentProfilePayload, S>

export type StudentProfileCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StudentProfileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StudentProfileCountAggregateInputType | true
  }

export interface StudentProfileDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['StudentProfile'], meta: { name: 'StudentProfile' } }
  /**
   * Find zero or one StudentProfile that matches the filter.
   * @param {StudentProfileFindUniqueArgs} args - Arguments to find a StudentProfile
   * @example
   * // Get one StudentProfile
   * const studentProfile = await prisma.studentProfile.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StudentProfileFindUniqueArgs>(args: Prisma.SelectSubset<T, StudentProfileFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StudentProfileClient<runtime.Types.Result.GetResult<Prisma.$StudentProfilePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one StudentProfile that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StudentProfileFindUniqueOrThrowArgs} args - Arguments to find a StudentProfile
   * @example
   * // Get one StudentProfile
   * const studentProfile = await prisma.studentProfile.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StudentProfileFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StudentProfileFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StudentProfileClient<runtime.Types.Result.GetResult<Prisma.$StudentProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StudentProfile that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentProfileFindFirstArgs} args - Arguments to find a StudentProfile
   * @example
   * // Get one StudentProfile
   * const studentProfile = await prisma.studentProfile.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StudentProfileFindFirstArgs>(args?: Prisma.SelectSubset<T, StudentProfileFindFirstArgs<ExtArgs>>): Prisma.Prisma__StudentProfileClient<runtime.Types.Result.GetResult<Prisma.$StudentProfilePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StudentProfile that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentProfileFindFirstOrThrowArgs} args - Arguments to find a StudentProfile
   * @example
   * // Get one StudentProfile
   * const studentProfile = await prisma.studentProfile.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StudentProfileFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StudentProfileFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StudentProfileClient<runtime.Types.Result.GetResult<Prisma.$StudentProfilePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more StudentProfiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentProfileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all StudentProfiles
   * const studentProfiles = await prisma.studentProfile.findMany()
   * 
   * // Get first 10 StudentProfiles
   * const studentProfiles = await prisma.studentProfile.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const studentProfileWithIdOnly = await prisma.studentProfile.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StudentProfileFindManyArgs>(args?: Prisma.SelectSubset<T, StudentProfileFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudentProfilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a StudentProfile.
   * @param {StudentProfileCreateArgs} args - Arguments to create a StudentProfile.
   * @example
   * // Create one StudentProfile
   * const StudentProfile = await prisma.studentProfile.create({
   *   data: {
   *     // ... data to create a StudentProfile
   *   }
   * })
   * 
   */
  create<T extends StudentProfileCreateArgs>(args: Prisma.SelectSubset<T, StudentProfileCreateArgs<ExtArgs>>): Prisma.Prisma__StudentProfileClient<runtime.Types.Result.GetResult<Prisma.$StudentProfilePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many StudentProfiles.
   * @param {StudentProfileCreateManyArgs} args - Arguments to create many StudentProfiles.
   * @example
   * // Create many StudentProfiles
   * const studentProfile = await prisma.studentProfile.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StudentProfileCreateManyArgs>(args?: Prisma.SelectSubset<T, StudentProfileCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many StudentProfiles and returns the data saved in the database.
   * @param {StudentProfileCreateManyAndReturnArgs} args - Arguments to create many StudentProfiles.
   * @example
   * // Create many StudentProfiles
   * const studentProfile = await prisma.studentProfile.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many StudentProfiles and only return the `id`
   * const studentProfileWithIdOnly = await prisma.studentProfile.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StudentProfileCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StudentProfileCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudentProfilePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a StudentProfile.
   * @param {StudentProfileDeleteArgs} args - Arguments to delete one StudentProfile.
   * @example
   * // Delete one StudentProfile
   * const StudentProfile = await prisma.studentProfile.delete({
   *   where: {
   *     // ... filter to delete one StudentProfile
   *   }
   * })
   * 
   */
  delete<T extends StudentProfileDeleteArgs>(args: Prisma.SelectSubset<T, StudentProfileDeleteArgs<ExtArgs>>): Prisma.Prisma__StudentProfileClient<runtime.Types.Result.GetResult<Prisma.$StudentProfilePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one StudentProfile.
   * @param {StudentProfileUpdateArgs} args - Arguments to update one StudentProfile.
   * @example
   * // Update one StudentProfile
   * const studentProfile = await prisma.studentProfile.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StudentProfileUpdateArgs>(args: Prisma.SelectSubset<T, StudentProfileUpdateArgs<ExtArgs>>): Prisma.Prisma__StudentProfileClient<runtime.Types.Result.GetResult<Prisma.$StudentProfilePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more StudentProfiles.
   * @param {StudentProfileDeleteManyArgs} args - Arguments to filter StudentProfiles to delete.
   * @example
   * // Delete a few StudentProfiles
   * const { count } = await prisma.studentProfile.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StudentProfileDeleteManyArgs>(args?: Prisma.SelectSubset<T, StudentProfileDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StudentProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentProfileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many StudentProfiles
   * const studentProfile = await prisma.studentProfile.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StudentProfileUpdateManyArgs>(args: Prisma.SelectSubset<T, StudentProfileUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StudentProfiles and returns the data updated in the database.
   * @param {StudentProfileUpdateManyAndReturnArgs} args - Arguments to update many StudentProfiles.
   * @example
   * // Update many StudentProfiles
   * const studentProfile = await prisma.studentProfile.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more StudentProfiles and only return the `id`
   * const studentProfileWithIdOnly = await prisma.studentProfile.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StudentProfileUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StudentProfileUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StudentProfilePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one StudentProfile.
   * @param {StudentProfileUpsertArgs} args - Arguments to update or create a StudentProfile.
   * @example
   * // Update or create a StudentProfile
   * const studentProfile = await prisma.studentProfile.upsert({
   *   create: {
   *     // ... data to create a StudentProfile
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the StudentProfile we want to update
   *   }
   * })
   */
  upsert<T extends StudentProfileUpsertArgs>(args: Prisma.SelectSubset<T, StudentProfileUpsertArgs<ExtArgs>>): Prisma.Prisma__StudentProfileClient<runtime.Types.Result.GetResult<Prisma.$StudentProfilePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of StudentProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentProfileCountArgs} args - Arguments to filter StudentProfiles to count.
   * @example
   * // Count the number of StudentProfiles
   * const count = await prisma.studentProfile.count({
   *   where: {
   *     // ... the filter for the StudentProfiles we want to count
   *   }
   * })
  **/
  count<T extends StudentProfileCountArgs>(
    args?: Prisma.Subset<T, StudentProfileCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StudentProfileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a StudentProfile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentProfileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StudentProfileAggregateArgs>(args: Prisma.Subset<T, StudentProfileAggregateArgs>): Prisma.PrismaPromise<GetStudentProfileAggregateType<T>>

  /**
   * Group by StudentProfile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StudentProfileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StudentProfileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StudentProfileGroupByArgs['orderBy'] }
      : { orderBy?: StudentProfileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StudentProfileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStudentProfileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the StudentProfile model
 */
readonly fields: StudentProfileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for StudentProfile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StudentProfileClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  ProjectGroup<T extends Prisma.StudentProfile$ProjectGroupArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StudentProfile$ProjectGroupArgs<ExtArgs>>): Prisma.Prisma__ProjectGroupClient<runtime.Types.Result.GetResult<Prisma.$ProjectGroupPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  User<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  Attendance<T extends Prisma.StudentProfile$AttendanceArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StudentProfile$AttendanceArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MeetingAttendancePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the StudentProfile model
 */
export interface StudentProfileFieldRefs {
  readonly id: Prisma.FieldRef<"StudentProfile", 'String'>
  readonly userId: Prisma.FieldRef<"StudentProfile", 'String'>
  readonly idNumber: Prisma.FieldRef<"StudentProfile", 'String'>
  readonly department: Prisma.FieldRef<"StudentProfile", 'String'>
  readonly batch: Prisma.FieldRef<"StudentProfile", 'String'>
  readonly groupId: Prisma.FieldRef<"StudentProfile", 'String'>
  readonly isLeader: Prisma.FieldRef<"StudentProfile", 'Boolean'>
}
    

// Custom InputTypes
/**
 * StudentProfile findUnique
 */
export type StudentProfileFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentProfile
   */
  select?: Prisma.StudentProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentProfile
   */
  omit?: Prisma.StudentProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentProfileInclude<ExtArgs> | null
  /**
   * Filter, which StudentProfile to fetch.
   */
  where: Prisma.StudentProfileWhereUniqueInput
}

/**
 * StudentProfile findUniqueOrThrow
 */
export type StudentProfileFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentProfile
   */
  select?: Prisma.StudentProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentProfile
   */
  omit?: Prisma.StudentProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentProfileInclude<ExtArgs> | null
  /**
   * Filter, which StudentProfile to fetch.
   */
  where: Prisma.StudentProfileWhereUniqueInput
}

/**
 * StudentProfile findFirst
 */
export type StudentProfileFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentProfile
   */
  select?: Prisma.StudentProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentProfile
   */
  omit?: Prisma.StudentProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentProfileInclude<ExtArgs> | null
  /**
   * Filter, which StudentProfile to fetch.
   */
  where?: Prisma.StudentProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StudentProfiles to fetch.
   */
  orderBy?: Prisma.StudentProfileOrderByWithRelationInput | Prisma.StudentProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StudentProfiles.
   */
  cursor?: Prisma.StudentProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StudentProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StudentProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StudentProfiles.
   */
  distinct?: Prisma.StudentProfileScalarFieldEnum | Prisma.StudentProfileScalarFieldEnum[]
}

/**
 * StudentProfile findFirstOrThrow
 */
export type StudentProfileFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentProfile
   */
  select?: Prisma.StudentProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentProfile
   */
  omit?: Prisma.StudentProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentProfileInclude<ExtArgs> | null
  /**
   * Filter, which StudentProfile to fetch.
   */
  where?: Prisma.StudentProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StudentProfiles to fetch.
   */
  orderBy?: Prisma.StudentProfileOrderByWithRelationInput | Prisma.StudentProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StudentProfiles.
   */
  cursor?: Prisma.StudentProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StudentProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StudentProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StudentProfiles.
   */
  distinct?: Prisma.StudentProfileScalarFieldEnum | Prisma.StudentProfileScalarFieldEnum[]
}

/**
 * StudentProfile findMany
 */
export type StudentProfileFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentProfile
   */
  select?: Prisma.StudentProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentProfile
   */
  omit?: Prisma.StudentProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentProfileInclude<ExtArgs> | null
  /**
   * Filter, which StudentProfiles to fetch.
   */
  where?: Prisma.StudentProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StudentProfiles to fetch.
   */
  orderBy?: Prisma.StudentProfileOrderByWithRelationInput | Prisma.StudentProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing StudentProfiles.
   */
  cursor?: Prisma.StudentProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StudentProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StudentProfiles.
   */
  skip?: number
  distinct?: Prisma.StudentProfileScalarFieldEnum | Prisma.StudentProfileScalarFieldEnum[]
}

/**
 * StudentProfile create
 */
export type StudentProfileCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentProfile
   */
  select?: Prisma.StudentProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentProfile
   */
  omit?: Prisma.StudentProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentProfileInclude<ExtArgs> | null
  /**
   * The data needed to create a StudentProfile.
   */
  data: Prisma.XOR<Prisma.StudentProfileCreateInput, Prisma.StudentProfileUncheckedCreateInput>
}

/**
 * StudentProfile createMany
 */
export type StudentProfileCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many StudentProfiles.
   */
  data: Prisma.StudentProfileCreateManyInput | Prisma.StudentProfileCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * StudentProfile createManyAndReturn
 */
export type StudentProfileCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentProfile
   */
  select?: Prisma.StudentProfileSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StudentProfile
   */
  omit?: Prisma.StudentProfileOmit<ExtArgs> | null
  /**
   * The data used to create many StudentProfiles.
   */
  data: Prisma.StudentProfileCreateManyInput | Prisma.StudentProfileCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentProfileIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * StudentProfile update
 */
export type StudentProfileUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentProfile
   */
  select?: Prisma.StudentProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentProfile
   */
  omit?: Prisma.StudentProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentProfileInclude<ExtArgs> | null
  /**
   * The data needed to update a StudentProfile.
   */
  data: Prisma.XOR<Prisma.StudentProfileUpdateInput, Prisma.StudentProfileUncheckedUpdateInput>
  /**
   * Choose, which StudentProfile to update.
   */
  where: Prisma.StudentProfileWhereUniqueInput
}

/**
 * StudentProfile updateMany
 */
export type StudentProfileUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update StudentProfiles.
   */
  data: Prisma.XOR<Prisma.StudentProfileUpdateManyMutationInput, Prisma.StudentProfileUncheckedUpdateManyInput>
  /**
   * Filter which StudentProfiles to update
   */
  where?: Prisma.StudentProfileWhereInput
  /**
   * Limit how many StudentProfiles to update.
   */
  limit?: number
}

/**
 * StudentProfile updateManyAndReturn
 */
export type StudentProfileUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentProfile
   */
  select?: Prisma.StudentProfileSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StudentProfile
   */
  omit?: Prisma.StudentProfileOmit<ExtArgs> | null
  /**
   * The data used to update StudentProfiles.
   */
  data: Prisma.XOR<Prisma.StudentProfileUpdateManyMutationInput, Prisma.StudentProfileUncheckedUpdateManyInput>
  /**
   * Filter which StudentProfiles to update
   */
  where?: Prisma.StudentProfileWhereInput
  /**
   * Limit how many StudentProfiles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentProfileIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * StudentProfile upsert
 */
export type StudentProfileUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentProfile
   */
  select?: Prisma.StudentProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentProfile
   */
  omit?: Prisma.StudentProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentProfileInclude<ExtArgs> | null
  /**
   * The filter to search for the StudentProfile to update in case it exists.
   */
  where: Prisma.StudentProfileWhereUniqueInput
  /**
   * In case the StudentProfile found by the `where` argument doesn't exist, create a new StudentProfile with this data.
   */
  create: Prisma.XOR<Prisma.StudentProfileCreateInput, Prisma.StudentProfileUncheckedCreateInput>
  /**
   * In case the StudentProfile was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StudentProfileUpdateInput, Prisma.StudentProfileUncheckedUpdateInput>
}

/**
 * StudentProfile delete
 */
export type StudentProfileDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentProfile
   */
  select?: Prisma.StudentProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentProfile
   */
  omit?: Prisma.StudentProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentProfileInclude<ExtArgs> | null
  /**
   * Filter which StudentProfile to delete.
   */
  where: Prisma.StudentProfileWhereUniqueInput
}

/**
 * StudentProfile deleteMany
 */
export type StudentProfileDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StudentProfiles to delete
   */
  where?: Prisma.StudentProfileWhereInput
  /**
   * Limit how many StudentProfiles to delete.
   */
  limit?: number
}

/**
 * StudentProfile.ProjectGroup
 */
export type StudentProfile$ProjectGroupArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProjectGroup
   */
  select?: Prisma.ProjectGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProjectGroup
   */
  omit?: Prisma.ProjectGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProjectGroupInclude<ExtArgs> | null
  where?: Prisma.ProjectGroupWhereInput
}

/**
 * StudentProfile.Attendance
 */
export type StudentProfile$AttendanceArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MeetingAttendance
   */
  select?: Prisma.MeetingAttendanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MeetingAttendance
   */
  omit?: Prisma.MeetingAttendanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MeetingAttendanceInclude<ExtArgs> | null
  where?: Prisma.MeetingAttendanceWhereInput
  orderBy?: Prisma.MeetingAttendanceOrderByWithRelationInput | Prisma.MeetingAttendanceOrderByWithRelationInput[]
  cursor?: Prisma.MeetingAttendanceWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MeetingAttendanceScalarFieldEnum | Prisma.MeetingAttendanceScalarFieldEnum[]
}

/**
 * StudentProfile without action
 */
export type StudentProfileDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StudentProfile
   */
  select?: Prisma.StudentProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StudentProfile
   */
  omit?: Prisma.StudentProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StudentProfileInclude<ExtArgs> | null
}
