
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Document
 * 
 */
export type Document = Prisma.DocumentModel
/**
 * Model FacultyProfile
 * 
 */
export type FacultyProfile = Prisma.FacultyProfileModel
/**
 * Model Meeting
 * 
 */
export type Meeting = Prisma.MeetingModel
/**
 * Model MeetingAttendance
 * 
 */
export type MeetingAttendance = Prisma.MeetingAttendanceModel
/**
 * Model Message
 * 
 */
export type Message = Prisma.MessageModel
/**
 * Model Milestone
 * 
 */
export type Milestone = Prisma.MilestoneModel
/**
 * Model Notification
 * 
 */
export type Notification = Prisma.NotificationModel
/**
 * Model Project
 * 
 */
export type Project = Prisma.ProjectModel
/**
 * Model ProjectType
 * 
 */
export type ProjectType = Prisma.ProjectTypeModel
/**
 * Model ProjectGroup
 * 
 */
export type ProjectGroup = Prisma.ProjectGroupModel
/**
 * Model StudentProfile
 * 
 */
export type StudentProfile = Prisma.StudentProfileModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Department
 * 
 */
export type Department = Prisma.DepartmentModel
/**
 * Model AcademicYear
 * 
 */
export type AcademicYear = Prisma.AcademicYearModel
