
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
export * from "./enums"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Documents
 * const documents = await prisma.document.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model Document
 * 
 */
export type Document = Prisma.DocumentModel
/**
 * Model FacultyProfile
 * 
 */
export type FacultyProfile = Prisma.FacultyProfileModel
/**
 * Model Meeting
 * 
 */
export type Meeting = Prisma.MeetingModel
/**
 * Model MeetingAttendance
 * 
 */
export type MeetingAttendance = Prisma.MeetingAttendanceModel
/**
 * Model Message
 * 
 */
export type Message = Prisma.MessageModel
/**
 * Model Milestone
 * 
 */
export type Milestone = Prisma.MilestoneModel
/**
 * Model Notification
 * 
 */
export type Notification = Prisma.NotificationModel
/**
 * Model Project
 * 
 */
export type Project = Prisma.ProjectModel
/**
 * Model ProjectType
 * 
 */
export type ProjectType = Prisma.ProjectTypeModel
/**
 * Model ProjectGroup
 * 
 */
export type ProjectGroup = Prisma.ProjectGroupModel
/**
 * Model StudentProfile
 * 
 */
export type StudentProfile = Prisma.StudentProfileModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Department
 * 
 */
export type Department = Prisma.DepartmentModel
/**
 * Model AcademicYear
 * 
 */
export type AcademicYear = Prisma.AcademicYearModel
