
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Document'
export type * from './models/FacultyProfile'
export type * from './models/Meeting'
export type * from './models/MeetingAttendance'
export type * from './models/Message'
export type * from './models/Milestone'
export type * from './models/Notification'
export type * from './models/Project'
export type * from './models/ProjectType'
export type * from './models/ProjectGroup'
export type * from './models/StudentProfile'
export type * from './models/User'
export type * from './models/Department'
export type * from './models/AcademicYear'
export type * from './commonInputTypes'